//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:2.0.50727.5485
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 
namespace MSAClass.AsmxVeiculo {
    using System.Xml.Serialization;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Diagnostics;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="asmxVeiculoSoap", Namespace="http://tempuri.org/")]
    public partial class asmxVeiculo : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private AuthSoapHd authSoapHdValueField;
        
        private System.Threading.SendOrPostCallback CreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback spuCarregarOperationCompleted;
        
        private System.Threading.SendOrPostCallback spuCarregar1OperationCompleted;
        
        /// <remarks/>
        public asmxVeiculo() {
            string urlSetting = System.Configuration.ConfigurationManager.AppSettings["url_AsmxVeiculo"];
            if ((urlSetting != null)) {
                this.Url = urlSetting;
            }
            else {
                this.Url = "http://localhost/WebServiceMSA/AsmxVeiculo.asmx";
            }
        }
        
        public AuthSoapHd AuthSoapHdValue {
            get {
                return this.authSoapHdValueField;
            }
            set {
                this.authSoapHdValueField = value;
            }
        }
        
        /// <remarks/>
        public event CreateCompletedEventHandler CreateCompleted;
        
        /// <remarks/>
        public event spuCarregarCompletedEventHandler spuCarregarCompleted;
        
        /// <remarks/>
        public event spuCarregar1CompletedEventHandler spuCarregar1Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Create", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public dtsVeiculo Create() {
            object[] results = this.Invoke("Create", new object[0]);
            return ((dtsVeiculo)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreate(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Create", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public dtsVeiculo EndCreate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((dtsVeiculo)(results[0]));
        }
        
        /// <remarks/>
        public void CreateAsync() {
            this.CreateAsync(null);
        }
        
        /// <remarks/>
        public void CreateAsync(object userState) {
            if ((this.CreateOperationCompleted == null)) {
                this.CreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOperationCompleted);
            }
            this.InvokeAsync("Create", new object[0], this.CreateOperationCompleted, userState);
        }
        
        private void OnCreateOperationCompleted(object arg) {
            if ((this.CreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCompleted(this, new CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/spuCarregarTudo", RequestElementName="spuCarregarTudo", RequestNamespace="http://tempuri.org/", ResponseElementName="spuCarregarTudoResponse", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("spuCarregarTudoResult")]
        public dtsVeiculo spuCarregar() {
            object[] results = this.Invoke("spuCarregar", new object[0]);
            return ((dtsVeiculo)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginspuCarregar(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("spuCarregar", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public dtsVeiculo EndspuCarregar(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((dtsVeiculo)(results[0]));
        }
        
        /// <remarks/>
        public void spuCarregarAsync() {
            this.spuCarregarAsync(null);
        }
        
        /// <remarks/>
        public void spuCarregarAsync(object userState) {
            if ((this.spuCarregarOperationCompleted == null)) {
                this.spuCarregarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnspuCarregarOperationCompleted);
            }
            this.InvokeAsync("spuCarregar", new object[0], this.spuCarregarOperationCompleted, userState);
        }
        
        private void OnspuCarregarOperationCompleted(object arg) {
            if ((this.spuCarregarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.spuCarregarCompleted(this, new spuCarregarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.WebMethodAttribute(MessageName="spuCarregar1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/spuCarregar", RequestElementName="spuCarregar", RequestNamespace="http://tempuri.org/", ResponseElementName="spuCarregarResponse", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("spuCarregarResult")]
        public dtsVeiculo spuCarregar(string strCod_Veiculo) {
            object[] results = this.Invoke("spuCarregar1", new object[] {
                        strCod_Veiculo});
            return ((dtsVeiculo)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginspuCarregar1(string strCod_Veiculo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("spuCarregar1", new object[] {
                        strCod_Veiculo}, callback, asyncState);
        }
        
        /// <remarks/>
        public dtsVeiculo EndspuCarregar1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((dtsVeiculo)(results[0]));
        }
        
        /// <remarks/>
        public void spuCarregar1Async(string strCod_Veiculo) {
            this.spuCarregar1Async(strCod_Veiculo, null);
        }
        
        /// <remarks/>
        public void spuCarregar1Async(string strCod_Veiculo, object userState) {
            if ((this.spuCarregar1OperationCompleted == null)) {
                this.spuCarregar1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnspuCarregar1OperationCompleted);
            }
            this.InvokeAsync("spuCarregar1", new object[] {
                        strCod_Veiculo}, this.spuCarregar1OperationCompleted, userState);
        }
        
        private void OnspuCarregar1OperationCompleted(object arg) {
            if ((this.spuCarregar1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.spuCarregar1Completed(this, new spuCarregar1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class AuthSoapHd : System.Web.Services.Protocols.SoapHeader {
        
        private string strUserNameField;
        
        private string strPasswordField;
        
        private string strKeyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string strUserName {
            get {
                return this.strUserNameField;
            }
            set {
                this.strUserNameField = value;
            }
        }
        
        /// <remarks/>
        public string strPassword {
            get {
                return this.strPasswordField;
            }
            set {
                this.strPasswordField = value;
            }
        }
        
        /// <remarks/>
        public string strKey {
            get {
                return this.strKeyField;
            }
            set {
                this.strKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    // A definição deste tipo foi gerada pela extensão do importador do esquema System.Data.Design.TypedDataSetSchemaImporterExtension.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dtsVeiculo")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dtsVeiculo : global::System.Data.DataSet {
        
        private dtbVeiculoDataTable tabledtbVeiculo;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public dtsVeiculo() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected dtsVeiculo(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["dtbVeiculo"] != null)) {
                    base.Tables.Add(new dtbVeiculoDataTable(ds.Tables["dtbVeiculo"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public dtbVeiculoDataTable dtbVeiculo {
            get {
                return this.tabledtbVeiculo;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            dtsVeiculo cln = ((dtsVeiculo)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["dtbVeiculo"] != null)) {
                    base.Tables.Add(new dtbVeiculoDataTable(ds.Tables["dtbVeiculo"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tabledtbVeiculo = ((dtbVeiculoDataTable)(base.Tables["dtbVeiculo"]));
            if ((initTable == true)) {
                if ((this.tabledtbVeiculo != null)) {
                    this.tabledtbVeiculo.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "dtsVeiculo";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dtsVeiculo.xsd";
            this.Locale = new global::System.Globalization.CultureInfo("en-US");
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tabledtbVeiculo = new dtbVeiculoDataTable();
            base.Tables.Add(this.tabledtbVeiculo);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializedtbVeiculo() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dtsVeiculo ds = new dtsVeiculo();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void dtbVeiculoRowChangeEventHandler(object sender, dtbVeiculoRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class dtbVeiculoDataTable : global::System.Data.DataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn columnCod_Veiculo;
            
            private global::System.Data.DataColumn columnAgencia;
            
            private global::System.Data.DataColumn columnBanco;
            
            private global::System.Data.DataColumn columnCidade;
            
            private global::System.Data.DataColumn columnCod_Empresa;
            
            private global::System.Data.DataColumn columnConta_Corrente;
            
            private global::System.Data.DataColumn columnData_Final;
            
            private global::System.Data.DataColumn columnData_Inicio;
            
            private global::System.Data.DataColumn columnEmail_Diretoria;
            
            private global::System.Data.DataColumn columnEmail_Faturamento;
            
            private global::System.Data.DataColumn columnEmail_Opec;
            
            private global::System.Data.DataColumn columnIndica_Filiada;
            
            private global::System.Data.DataColumn columnNet;
            
            private global::System.Data.DataColumn columnNome_Veiculo;
            
            private global::System.Data.DataColumn columnResponsavel;
            
            private global::System.Data.DataColumn columnSigla_Veiculo;
            
            private global::System.Data.DataColumn columnPercentual_Contratual;
            
            private global::System.Data.DataColumn columnIndica_Roteiro;
            
            private global::System.Data.DataColumn columnApelido;
            
            private global::System.Data.DataColumn columnIndica_Integracao;
            
            private global::System.Data.DataColumn columnPercentual_Repasse_Varejo;
            
            private global::System.Data.DataColumn columnCod_Veiculo_Link;
            
            private global::System.Data.DataColumn columnSigla_Roteiro;
            
            private global::System.Data.DataColumn columnHora_Inicio_Programacao;
            
            private global::System.Data.DataColumn columnindica_ordenacao_pe;
            
            private global::System.Data.DataColumn columnSigla_JOVE;
            
            private global::System.Data.DataColumn columnLimite_Envio_Digitacao;
            
            private global::System.Data.DataColumn columnMsg_MMA;
            
            private global::System.Data.DataColumn columnOcultar_MMA;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public dtbVeiculoDataTable() {
                this.TableName = "dtbVeiculo";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal dtbVeiculoDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected dtbVeiculoDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Cod_VeiculoColumn {
                get {
                    return this.columnCod_Veiculo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn AgenciaColumn {
                get {
                    return this.columnAgencia;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn BancoColumn {
                get {
                    return this.columnBanco;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CidadeColumn {
                get {
                    return this.columnCidade;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Cod_EmpresaColumn {
                get {
                    return this.columnCod_Empresa;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Conta_CorrenteColumn {
                get {
                    return this.columnConta_Corrente;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Data_FinalColumn {
                get {
                    return this.columnData_Final;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Data_InicioColumn {
                get {
                    return this.columnData_Inicio;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Email_DiretoriaColumn {
                get {
                    return this.columnEmail_Diretoria;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Email_FaturamentoColumn {
                get {
                    return this.columnEmail_Faturamento;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Email_OpecColumn {
                get {
                    return this.columnEmail_Opec;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Indica_FiliadaColumn {
                get {
                    return this.columnIndica_Filiada;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn NetColumn {
                get {
                    return this.columnNet;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Nome_VeiculoColumn {
                get {
                    return this.columnNome_Veiculo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ResponsavelColumn {
                get {
                    return this.columnResponsavel;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Sigla_VeiculoColumn {
                get {
                    return this.columnSigla_Veiculo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Percentual_ContratualColumn {
                get {
                    return this.columnPercentual_Contratual;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Indica_RoteiroColumn {
                get {
                    return this.columnIndica_Roteiro;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ApelidoColumn {
                get {
                    return this.columnApelido;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Indica_IntegracaoColumn {
                get {
                    return this.columnIndica_Integracao;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Percentual_Repasse_VarejoColumn {
                get {
                    return this.columnPercentual_Repasse_Varejo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Cod_Veiculo_LinkColumn {
                get {
                    return this.columnCod_Veiculo_Link;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Sigla_RoteiroColumn {
                get {
                    return this.columnSigla_Roteiro;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Hora_Inicio_ProgramacaoColumn {
                get {
                    return this.columnHora_Inicio_Programacao;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn indica_ordenacao_peColumn {
                get {
                    return this.columnindica_ordenacao_pe;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Sigla_JOVEColumn {
                get {
                    return this.columnSigla_JOVE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Limite_Envio_DigitacaoColumn {
                get {
                    return this.columnLimite_Envio_Digitacao;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Msg_MMAColumn {
                get {
                    return this.columnMsg_MMA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Ocultar_MMAColumn {
                get {
                    return this.columnOcultar_MMA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public dtbVeiculoRow this[int index] {
                get {
                    return ((dtbVeiculoRow)(this.Rows[index]));
                }
            }
            
            public event dtbVeiculoRowChangeEventHandler dtbVeiculoRowChanging;
            
            public event dtbVeiculoRowChangeEventHandler dtbVeiculoRowChanged;
            
            public event dtbVeiculoRowChangeEventHandler dtbVeiculoRowDeleting;
            
            public event dtbVeiculoRowChangeEventHandler dtbVeiculoRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AdddtbVeiculoRow(dtbVeiculoRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public dtbVeiculoRow AdddtbVeiculoRow(
                        string Cod_Veiculo, 
                        string Agencia, 
                        string Banco, 
                        string Cidade, 
                        string Cod_Empresa, 
                        string Conta_Corrente, 
                        System.DateTime Data_Final, 
                        System.DateTime Data_Inicio, 
                        string Email_Diretoria, 
                        string Email_Faturamento, 
                        string Email_Opec, 
                        byte Indica_Filiada, 
                        byte Net, 
                        string Nome_Veiculo, 
                        string Responsavel, 
                        string Sigla_Veiculo, 
                        decimal Percentual_Contratual, 
                        byte Indica_Roteiro, 
                        string Apelido, 
                        byte Indica_Integracao, 
                        decimal Percentual_Repasse_Varejo, 
                        string Cod_Veiculo_Link, 
                        string Sigla_Roteiro, 
                        string Hora_Inicio_Programacao, 
                        byte indica_ordenacao_pe, 
                        string Sigla_JOVE, 
                        byte Limite_Envio_Digitacao, 
                        string Msg_MMA, 
                        bool Ocultar_MMA) {
                dtbVeiculoRow rowdtbVeiculoRow = ((dtbVeiculoRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        Cod_Veiculo,
                        Agencia,
                        Banco,
                        Cidade,
                        Cod_Empresa,
                        Conta_Corrente,
                        Data_Final,
                        Data_Inicio,
                        Email_Diretoria,
                        Email_Faturamento,
                        Email_Opec,
                        Indica_Filiada,
                        Net,
                        Nome_Veiculo,
                        Responsavel,
                        Sigla_Veiculo,
                        Percentual_Contratual,
                        Indica_Roteiro,
                        Apelido,
                        Indica_Integracao,
                        Percentual_Repasse_Varejo,
                        Cod_Veiculo_Link,
                        Sigla_Roteiro,
                        Hora_Inicio_Programacao,
                        indica_ordenacao_pe,
                        Sigla_JOVE,
                        Limite_Envio_Digitacao,
                        Msg_MMA,
                        Ocultar_MMA};
                rowdtbVeiculoRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowdtbVeiculoRow);
                return rowdtbVeiculoRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public dtbVeiculoRow FindByCod_Veiculo(string Cod_Veiculo) {
                return ((dtbVeiculoRow)(this.Rows.Find(new object[] {
                            Cod_Veiculo})));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                dtbVeiculoDataTable cln = ((dtbVeiculoDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new dtbVeiculoDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnCod_Veiculo = base.Columns["Cod_Veiculo"];
                this.columnAgencia = base.Columns["Agencia"];
                this.columnBanco = base.Columns["Banco"];
                this.columnCidade = base.Columns["Cidade"];
                this.columnCod_Empresa = base.Columns["Cod_Empresa"];
                this.columnConta_Corrente = base.Columns["Conta_Corrente"];
                this.columnData_Final = base.Columns["Data_Final"];
                this.columnData_Inicio = base.Columns["Data_Inicio"];
                this.columnEmail_Diretoria = base.Columns["Email_Diretoria"];
                this.columnEmail_Faturamento = base.Columns["Email_Faturamento"];
                this.columnEmail_Opec = base.Columns["Email_Opec"];
                this.columnIndica_Filiada = base.Columns["Indica_Filiada"];
                this.columnNet = base.Columns["Net"];
                this.columnNome_Veiculo = base.Columns["Nome_Veiculo"];
                this.columnResponsavel = base.Columns["Responsavel"];
                this.columnSigla_Veiculo = base.Columns["Sigla_Veiculo"];
                this.columnPercentual_Contratual = base.Columns["Percentual_Contratual"];
                this.columnIndica_Roteiro = base.Columns["Indica_Roteiro"];
                this.columnApelido = base.Columns["Apelido"];
                this.columnIndica_Integracao = base.Columns["Indica_Integracao"];
                this.columnPercentual_Repasse_Varejo = base.Columns["Percentual_Repasse_Varejo"];
                this.columnCod_Veiculo_Link = base.Columns["Cod_Veiculo_Link"];
                this.columnSigla_Roteiro = base.Columns["Sigla_Roteiro"];
                this.columnHora_Inicio_Programacao = base.Columns["Hora_Inicio_Programacao"];
                this.columnindica_ordenacao_pe = base.Columns["indica_ordenacao_pe"];
                this.columnSigla_JOVE = base.Columns["Sigla_JOVE"];
                this.columnLimite_Envio_Digitacao = base.Columns["Limite_Envio_Digitacao"];
                this.columnMsg_MMA = base.Columns["Msg_MMA"];
                this.columnOcultar_MMA = base.Columns["Ocultar_MMA"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnCod_Veiculo = new global::System.Data.DataColumn("Cod_Veiculo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCod_Veiculo);
                this.columnAgencia = new global::System.Data.DataColumn("Agencia", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAgencia);
                this.columnBanco = new global::System.Data.DataColumn("Banco", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBanco);
                this.columnCidade = new global::System.Data.DataColumn("Cidade", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCidade);
                this.columnCod_Empresa = new global::System.Data.DataColumn("Cod_Empresa", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCod_Empresa);
                this.columnConta_Corrente = new global::System.Data.DataColumn("Conta_Corrente", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnConta_Corrente);
                this.columnData_Final = new global::System.Data.DataColumn("Data_Final", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnData_Final);
                this.columnData_Inicio = new global::System.Data.DataColumn("Data_Inicio", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnData_Inicio);
                this.columnEmail_Diretoria = new global::System.Data.DataColumn("Email_Diretoria", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnEmail_Diretoria);
                this.columnEmail_Faturamento = new global::System.Data.DataColumn("Email_Faturamento", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnEmail_Faturamento);
                this.columnEmail_Opec = new global::System.Data.DataColumn("Email_Opec", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnEmail_Opec);
                this.columnIndica_Filiada = new global::System.Data.DataColumn("Indica_Filiada", typeof(byte), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIndica_Filiada);
                this.columnNet = new global::System.Data.DataColumn("Net", typeof(byte), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNet);
                this.columnNome_Veiculo = new global::System.Data.DataColumn("Nome_Veiculo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNome_Veiculo);
                this.columnResponsavel = new global::System.Data.DataColumn("Responsavel", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnResponsavel);
                this.columnSigla_Veiculo = new global::System.Data.DataColumn("Sigla_Veiculo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSigla_Veiculo);
                this.columnPercentual_Contratual = new global::System.Data.DataColumn("Percentual_Contratual", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPercentual_Contratual);
                this.columnIndica_Roteiro = new global::System.Data.DataColumn("Indica_Roteiro", typeof(byte), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIndica_Roteiro);
                this.columnApelido = new global::System.Data.DataColumn("Apelido", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnApelido);
                this.columnIndica_Integracao = new global::System.Data.DataColumn("Indica_Integracao", typeof(byte), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIndica_Integracao);
                this.columnPercentual_Repasse_Varejo = new global::System.Data.DataColumn("Percentual_Repasse_Varejo", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPercentual_Repasse_Varejo);
                this.columnCod_Veiculo_Link = new global::System.Data.DataColumn("Cod_Veiculo_Link", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCod_Veiculo_Link);
                this.columnSigla_Roteiro = new global::System.Data.DataColumn("Sigla_Roteiro", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSigla_Roteiro);
                this.columnHora_Inicio_Programacao = new global::System.Data.DataColumn("Hora_Inicio_Programacao", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnHora_Inicio_Programacao);
                this.columnindica_ordenacao_pe = new global::System.Data.DataColumn("indica_ordenacao_pe", typeof(byte), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnindica_ordenacao_pe);
                this.columnSigla_JOVE = new global::System.Data.DataColumn("Sigla_JOVE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSigla_JOVE);
                this.columnLimite_Envio_Digitacao = new global::System.Data.DataColumn("Limite_Envio_Digitacao", typeof(byte), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnLimite_Envio_Digitacao);
                this.columnMsg_MMA = new global::System.Data.DataColumn("Msg_MMA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMsg_MMA);
                this.columnOcultar_MMA = new global::System.Data.DataColumn("Ocultar_MMA", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOcultar_MMA);
                this.Constraints.Add(new global::System.Data.UniqueConstraint("Constraint1", new global::System.Data.DataColumn[] {
                                this.columnCod_Veiculo}, true));
                this.columnCod_Veiculo.AllowDBNull = false;
                this.columnCod_Veiculo.Unique = true;
                this.columnCod_Veiculo.MaxLength = 3;
                this.columnAgencia.MaxLength = 4;
                this.columnBanco.MaxLength = 3;
                this.columnCidade.MaxLength = 30;
                this.columnCod_Empresa.MaxLength = 3;
                this.columnConta_Corrente.MaxLength = 10;
                this.columnEmail_Diretoria.MaxLength = 30;
                this.columnEmail_Faturamento.MaxLength = 30;
                this.columnEmail_Opec.MaxLength = 100;
                this.columnNet.AllowDBNull = false;
                this.columnNome_Veiculo.MaxLength = 50;
                this.columnResponsavel.MaxLength = 30;
                this.columnSigla_Veiculo.MaxLength = 5;
                this.columnPercentual_Contratual.AllowDBNull = false;
                this.columnApelido.MaxLength = 30;
                this.columnCod_Veiculo_Link.MaxLength = 3;
                this.columnSigla_Roteiro.MaxLength = 2;
                this.columnHora_Inicio_Programacao.MaxLength = 5;
                this.columnSigla_JOVE.MaxLength = 3;
                this.columnMsg_MMA.MaxLength = 500;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public dtbVeiculoRow NewdtbVeiculoRow() {
                return ((dtbVeiculoRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new dtbVeiculoRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(dtbVeiculoRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.dtbVeiculoRowChanged != null)) {
                    this.dtbVeiculoRowChanged(this, new dtbVeiculoRowChangeEvent(((dtbVeiculoRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.dtbVeiculoRowChanging != null)) {
                    this.dtbVeiculoRowChanging(this, new dtbVeiculoRowChangeEvent(((dtbVeiculoRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.dtbVeiculoRowDeleted != null)) {
                    this.dtbVeiculoRowDeleted(this, new dtbVeiculoRowChangeEvent(((dtbVeiculoRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.dtbVeiculoRowDeleting != null)) {
                    this.dtbVeiculoRowDeleting(this, new dtbVeiculoRowChangeEvent(((dtbVeiculoRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemovedtbVeiculoRow(dtbVeiculoRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dtsVeiculo ds = new dtsVeiculo();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "dtbVeiculoDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class dtbVeiculoRow : global::System.Data.DataRow {
            
            private dtbVeiculoDataTable tabledtbVeiculo;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal dtbVeiculoRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tabledtbVeiculo = ((dtbVeiculoDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Cod_Veiculo {
                get {
                    return ((string)(this[this.tabledtbVeiculo.Cod_VeiculoColumn]));
                }
                set {
                    this[this.tabledtbVeiculo.Cod_VeiculoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Agencia {
                get {
                    try {
                        return ((string)(this[this.tabledtbVeiculo.AgenciaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Agencia\' na tabela \'dtbVeiculo\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbVeiculo.AgenciaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Banco {
                get {
                    try {
                        return ((string)(this[this.tabledtbVeiculo.BancoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Banco\' na tabela \'dtbVeiculo\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbVeiculo.BancoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Cidade {
                get {
                    try {
                        return ((string)(this[this.tabledtbVeiculo.CidadeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Cidade\' na tabela \'dtbVeiculo\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbVeiculo.CidadeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Cod_Empresa {
                get {
                    try {
                        return ((string)(this[this.tabledtbVeiculo.Cod_EmpresaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Cod_Empresa\' na tabela \'dtbVeiculo\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbVeiculo.Cod_EmpresaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Conta_Corrente {
                get {
                    try {
                        return ((string)(this[this.tabledtbVeiculo.Conta_CorrenteColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Conta_Corrente\' na tabela \'dtbVeiculo\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbVeiculo.Conta_CorrenteColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime Data_Final {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tabledtbVeiculo.Data_FinalColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Data_Final\' na tabela \'dtbVeiculo\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbVeiculo.Data_FinalColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime Data_Inicio {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tabledtbVeiculo.Data_InicioColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Data_Inicio\' na tabela \'dtbVeiculo\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbVeiculo.Data_InicioColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Email_Diretoria {
                get {
                    try {
                        return ((string)(this[this.tabledtbVeiculo.Email_DiretoriaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Email_Diretoria\' na tabela \'dtbVeiculo\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbVeiculo.Email_DiretoriaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Email_Faturamento {
                get {
                    try {
                        return ((string)(this[this.tabledtbVeiculo.Email_FaturamentoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Email_Faturamento\' na tabela \'dtbVeiculo\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbVeiculo.Email_FaturamentoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Email_Opec {
                get {
                    try {
                        return ((string)(this[this.tabledtbVeiculo.Email_OpecColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Email_Opec\' na tabela \'dtbVeiculo\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbVeiculo.Email_OpecColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public byte Indica_Filiada {
                get {
                    try {
                        return ((byte)(this[this.tabledtbVeiculo.Indica_FiliadaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Indica_Filiada\' na tabela \'dtbVeiculo\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbVeiculo.Indica_FiliadaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public byte Net {
                get {
                    return ((byte)(this[this.tabledtbVeiculo.NetColumn]));
                }
                set {
                    this[this.tabledtbVeiculo.NetColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Nome_Veiculo {
                get {
                    try {
                        return ((string)(this[this.tabledtbVeiculo.Nome_VeiculoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Nome_Veiculo\' na tabela \'dtbVeiculo\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbVeiculo.Nome_VeiculoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Responsavel {
                get {
                    try {
                        return ((string)(this[this.tabledtbVeiculo.ResponsavelColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Responsavel\' na tabela \'dtbVeiculo\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbVeiculo.ResponsavelColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Sigla_Veiculo {
                get {
                    try {
                        return ((string)(this[this.tabledtbVeiculo.Sigla_VeiculoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Sigla_Veiculo\' na tabela \'dtbVeiculo\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbVeiculo.Sigla_VeiculoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal Percentual_Contratual {
                get {
                    return ((decimal)(this[this.tabledtbVeiculo.Percentual_ContratualColumn]));
                }
                set {
                    this[this.tabledtbVeiculo.Percentual_ContratualColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public byte Indica_Roteiro {
                get {
                    try {
                        return ((byte)(this[this.tabledtbVeiculo.Indica_RoteiroColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Indica_Roteiro\' na tabela \'dtbVeiculo\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbVeiculo.Indica_RoteiroColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Apelido {
                get {
                    try {
                        return ((string)(this[this.tabledtbVeiculo.ApelidoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Apelido\' na tabela \'dtbVeiculo\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbVeiculo.ApelidoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public byte Indica_Integracao {
                get {
                    try {
                        return ((byte)(this[this.tabledtbVeiculo.Indica_IntegracaoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Indica_Integracao\' na tabela \'dtbVeiculo\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbVeiculo.Indica_IntegracaoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal Percentual_Repasse_Varejo {
                get {
                    try {
                        return ((decimal)(this[this.tabledtbVeiculo.Percentual_Repasse_VarejoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Percentual_Repasse_Varejo\' na tabela \'dtbVeiculo\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbVeiculo.Percentual_Repasse_VarejoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Cod_Veiculo_Link {
                get {
                    try {
                        return ((string)(this[this.tabledtbVeiculo.Cod_Veiculo_LinkColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Cod_Veiculo_Link\' na tabela \'dtbVeiculo\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbVeiculo.Cod_Veiculo_LinkColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Sigla_Roteiro {
                get {
                    try {
                        return ((string)(this[this.tabledtbVeiculo.Sigla_RoteiroColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Sigla_Roteiro\' na tabela \'dtbVeiculo\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbVeiculo.Sigla_RoteiroColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Hora_Inicio_Programacao {
                get {
                    try {
                        return ((string)(this[this.tabledtbVeiculo.Hora_Inicio_ProgramacaoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Hora_Inicio_Programacao\' na tabela \'dtbVeiculo\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbVeiculo.Hora_Inicio_ProgramacaoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public byte indica_ordenacao_pe {
                get {
                    try {
                        return ((byte)(this[this.tabledtbVeiculo.indica_ordenacao_peColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'indica_ordenacao_pe\' na tabela \'dtbVeiculo\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbVeiculo.indica_ordenacao_peColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Sigla_JOVE {
                get {
                    try {
                        return ((string)(this[this.tabledtbVeiculo.Sigla_JOVEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Sigla_JOVE\' na tabela \'dtbVeiculo\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbVeiculo.Sigla_JOVEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public byte Limite_Envio_Digitacao {
                get {
                    try {
                        return ((byte)(this[this.tabledtbVeiculo.Limite_Envio_DigitacaoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Limite_Envio_Digitacao\' na tabela \'dtbVeiculo\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbVeiculo.Limite_Envio_DigitacaoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Msg_MMA {
                get {
                    try {
                        return ((string)(this[this.tabledtbVeiculo.Msg_MMAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Msg_MMA\' na tabela \'dtbVeiculo\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbVeiculo.Msg_MMAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Ocultar_MMA {
                get {
                    try {
                        return ((bool)(this[this.tabledtbVeiculo.Ocultar_MMAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Ocultar_MMA\' na tabela \'dtbVeiculo\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbVeiculo.Ocultar_MMAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsAgenciaNull() {
                return this.IsNull(this.tabledtbVeiculo.AgenciaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetAgenciaNull() {
                this[this.tabledtbVeiculo.AgenciaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsBancoNull() {
                return this.IsNull(this.tabledtbVeiculo.BancoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetBancoNull() {
                this[this.tabledtbVeiculo.BancoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCidadeNull() {
                return this.IsNull(this.tabledtbVeiculo.CidadeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCidadeNull() {
                this[this.tabledtbVeiculo.CidadeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCod_EmpresaNull() {
                return this.IsNull(this.tabledtbVeiculo.Cod_EmpresaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCod_EmpresaNull() {
                this[this.tabledtbVeiculo.Cod_EmpresaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsConta_CorrenteNull() {
                return this.IsNull(this.tabledtbVeiculo.Conta_CorrenteColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetConta_CorrenteNull() {
                this[this.tabledtbVeiculo.Conta_CorrenteColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsData_FinalNull() {
                return this.IsNull(this.tabledtbVeiculo.Data_FinalColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetData_FinalNull() {
                this[this.tabledtbVeiculo.Data_FinalColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsData_InicioNull() {
                return this.IsNull(this.tabledtbVeiculo.Data_InicioColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetData_InicioNull() {
                this[this.tabledtbVeiculo.Data_InicioColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsEmail_DiretoriaNull() {
                return this.IsNull(this.tabledtbVeiculo.Email_DiretoriaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetEmail_DiretoriaNull() {
                this[this.tabledtbVeiculo.Email_DiretoriaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsEmail_FaturamentoNull() {
                return this.IsNull(this.tabledtbVeiculo.Email_FaturamentoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetEmail_FaturamentoNull() {
                this[this.tabledtbVeiculo.Email_FaturamentoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsEmail_OpecNull() {
                return this.IsNull(this.tabledtbVeiculo.Email_OpecColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetEmail_OpecNull() {
                this[this.tabledtbVeiculo.Email_OpecColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsIndica_FiliadaNull() {
                return this.IsNull(this.tabledtbVeiculo.Indica_FiliadaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetIndica_FiliadaNull() {
                this[this.tabledtbVeiculo.Indica_FiliadaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsNome_VeiculoNull() {
                return this.IsNull(this.tabledtbVeiculo.Nome_VeiculoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetNome_VeiculoNull() {
                this[this.tabledtbVeiculo.Nome_VeiculoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsResponsavelNull() {
                return this.IsNull(this.tabledtbVeiculo.ResponsavelColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetResponsavelNull() {
                this[this.tabledtbVeiculo.ResponsavelColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSigla_VeiculoNull() {
                return this.IsNull(this.tabledtbVeiculo.Sigla_VeiculoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSigla_VeiculoNull() {
                this[this.tabledtbVeiculo.Sigla_VeiculoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsIndica_RoteiroNull() {
                return this.IsNull(this.tabledtbVeiculo.Indica_RoteiroColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetIndica_RoteiroNull() {
                this[this.tabledtbVeiculo.Indica_RoteiroColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsApelidoNull() {
                return this.IsNull(this.tabledtbVeiculo.ApelidoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetApelidoNull() {
                this[this.tabledtbVeiculo.ApelidoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsIndica_IntegracaoNull() {
                return this.IsNull(this.tabledtbVeiculo.Indica_IntegracaoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetIndica_IntegracaoNull() {
                this[this.tabledtbVeiculo.Indica_IntegracaoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPercentual_Repasse_VarejoNull() {
                return this.IsNull(this.tabledtbVeiculo.Percentual_Repasse_VarejoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPercentual_Repasse_VarejoNull() {
                this[this.tabledtbVeiculo.Percentual_Repasse_VarejoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCod_Veiculo_LinkNull() {
                return this.IsNull(this.tabledtbVeiculo.Cod_Veiculo_LinkColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCod_Veiculo_LinkNull() {
                this[this.tabledtbVeiculo.Cod_Veiculo_LinkColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSigla_RoteiroNull() {
                return this.IsNull(this.tabledtbVeiculo.Sigla_RoteiroColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSigla_RoteiroNull() {
                this[this.tabledtbVeiculo.Sigla_RoteiroColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsHora_Inicio_ProgramacaoNull() {
                return this.IsNull(this.tabledtbVeiculo.Hora_Inicio_ProgramacaoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetHora_Inicio_ProgramacaoNull() {
                this[this.tabledtbVeiculo.Hora_Inicio_ProgramacaoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isindica_ordenacao_peNull() {
                return this.IsNull(this.tabledtbVeiculo.indica_ordenacao_peColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setindica_ordenacao_peNull() {
                this[this.tabledtbVeiculo.indica_ordenacao_peColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSigla_JOVENull() {
                return this.IsNull(this.tabledtbVeiculo.Sigla_JOVEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSigla_JOVENull() {
                this[this.tabledtbVeiculo.Sigla_JOVEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsLimite_Envio_DigitacaoNull() {
                return this.IsNull(this.tabledtbVeiculo.Limite_Envio_DigitacaoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetLimite_Envio_DigitacaoNull() {
                this[this.tabledtbVeiculo.Limite_Envio_DigitacaoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsMsg_MMANull() {
                return this.IsNull(this.tabledtbVeiculo.Msg_MMAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetMsg_MMANull() {
                this[this.tabledtbVeiculo.Msg_MMAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsOcultar_MMANull() {
                return this.IsNull(this.tabledtbVeiculo.Ocultar_MMAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetOcultar_MMANull() {
                this[this.tabledtbVeiculo.Ocultar_MMAColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class dtbVeiculoRowChangeEvent : global::System.EventArgs {
            
            private dtbVeiculoRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public dtbVeiculoRowChangeEvent(dtbVeiculoRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public dtbVeiculoRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void CreateCompletedEventHandler(object sender, CreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public dtsVeiculo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((dtsVeiculo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void spuCarregarCompletedEventHandler(object sender, spuCarregarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class spuCarregarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal spuCarregarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public dtsVeiculo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((dtsVeiculo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void spuCarregar1CompletedEventHandler(object sender, spuCarregar1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class spuCarregar1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal spuCarregar1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public dtsVeiculo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((dtsVeiculo)(this.results[0]));
            }
        }
    }
}
