//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:2.0.50727.5485
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 
namespace MSAClass.AsmxContrato {
    using System.Xml.Serialization;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Diagnostics;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="asmxContratoSoap", Namespace="http://tempuri.org/")]
    public partial class asmxContrato : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private AuthSoapHd authSoapHdValueField;
        
        private System.Threading.SendOrPostCallback fnDefineDatasetOperationCompleted;
        
        private System.Threading.SendOrPostCallback fnNovoNumeroOperationCompleted;
        
        private System.Threading.SendOrPostCallback fnCarregaGradeOperationCompleted;
        
        private System.Threading.SendOrPostCallback fnVeiculoUsuarioCarregarOperationCompleted;
        
        private System.Threading.SendOrPostCallback fnConsisteCaracteristicaVeiculacaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback fnCriaNegociacaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback FnSalvarOperationCompleted;
        
        private System.Threading.SendOrPostCallback fnIemOperationCompleted;
        
        private System.Threading.SendOrPostCallback fnReabreCEOperationCompleted;
        
        private System.Threading.SendOrPostCallback fnIEVOperationCompleted;
        
        private System.Threading.SendOrPostCallback fnExisteMrOperationCompleted;
        
        private System.Threading.SendOrPostCallback fnUltimaSequenciaOperationCompleted;
        
        private System.Threading.SendOrPostCallback fnCarregaContratoOperationCompleted;
        
        private System.Threading.SendOrPostCallback fnDeterminacao_Dados_ContratoOperationCompleted;
        
        private System.Threading.SendOrPostCallback fnDeterminacao_Dados_ComercialOperationCompleted;
        
        private System.Threading.SendOrPostCallback fnDeterminacao_SelectOperationCompleted;
        
        private System.Threading.SendOrPostCallback fnDeterminacaoPendenteOperationCompleted;
        
        private System.Threading.SendOrPostCallback fnDeterminacao_Veiculo_SelectOperationCompleted;
        
        private System.Threading.SendOrPostCallback fnDeterminacao_DeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback fnDeterminacao_InsertOperationCompleted;
        
        private System.Threading.SendOrPostCallback fnDeterminacao_ComerciaisOperationCompleted;
        
        private System.Threading.SendOrPostCallback fnExisteComercialOperationCompleted;
        
        private System.Threading.SendOrPostCallback fnExcluirComercialOperationCompleted;
        
        /// <remarks/>
        public asmxContrato() {
            string urlSetting = System.Configuration.ConfigurationManager.AppSettings["url_AsmxContrato"];
            if ((urlSetting != null)) {
                this.Url = urlSetting;
            }
            else {
                this.Url = "http://localhost/WebServiceMSA/AsmxContrato.asmx";
            }
        }
        
        public AuthSoapHd AuthSoapHdValue {
            get {
                return this.authSoapHdValueField;
            }
            set {
                this.authSoapHdValueField = value;
            }
        }
        
        /// <remarks/>
        public event fnDefineDatasetCompletedEventHandler fnDefineDatasetCompleted;
        
        /// <remarks/>
        public event fnNovoNumeroCompletedEventHandler fnNovoNumeroCompleted;
        
        /// <remarks/>
        public event fnCarregaGradeCompletedEventHandler fnCarregaGradeCompleted;
        
        /// <remarks/>
        public event fnVeiculoUsuarioCarregarCompletedEventHandler fnVeiculoUsuarioCarregarCompleted;
        
        /// <remarks/>
        public event fnConsisteCaracteristicaVeiculacaoCompletedEventHandler fnConsisteCaracteristicaVeiculacaoCompleted;
        
        /// <remarks/>
        public event fnCriaNegociacaoCompletedEventHandler fnCriaNegociacaoCompleted;
        
        /// <remarks/>
        public event FnSalvarCompletedEventHandler FnSalvarCompleted;
        
        /// <remarks/>
        public event fnIemCompletedEventHandler fnIemCompleted;
        
        /// <remarks/>
        public event fnReabreCECompletedEventHandler fnReabreCECompleted;
        
        /// <remarks/>
        public event fnIEVCompletedEventHandler fnIEVCompleted;
        
        /// <remarks/>
        public event fnExisteMrCompletedEventHandler fnExisteMrCompleted;
        
        /// <remarks/>
        public event fnUltimaSequenciaCompletedEventHandler fnUltimaSequenciaCompleted;
        
        /// <remarks/>
        public event fnCarregaContratoCompletedEventHandler fnCarregaContratoCompleted;
        
        /// <remarks/>
        public event fnDeterminacao_Dados_ContratoCompletedEventHandler fnDeterminacao_Dados_ContratoCompleted;
        
        /// <remarks/>
        public event fnDeterminacao_Dados_ComercialCompletedEventHandler fnDeterminacao_Dados_ComercialCompleted;
        
        /// <remarks/>
        public event fnDeterminacao_SelectCompletedEventHandler fnDeterminacao_SelectCompleted;
        
        /// <remarks/>
        public event fnDeterminacaoPendenteCompletedEventHandler fnDeterminacaoPendenteCompleted;
        
        /// <remarks/>
        public event fnDeterminacao_Veiculo_SelectCompletedEventHandler fnDeterminacao_Veiculo_SelectCompleted;
        
        /// <remarks/>
        public event fnDeterminacao_DeleteCompletedEventHandler fnDeterminacao_DeleteCompleted;
        
        /// <remarks/>
        public event fnDeterminacao_InsertCompletedEventHandler fnDeterminacao_InsertCompleted;
        
        /// <remarks/>
        public event fnDeterminacao_ComerciaisCompletedEventHandler fnDeterminacao_ComerciaisCompleted;
        
        /// <remarks/>
        public event fnExisteComercialCompletedEventHandler fnExisteComercialCompleted;
        
        /// <remarks/>
        public event fnExcluirComercialCompletedEventHandler fnExcluirComercialCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fnDefineDataset", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet fnDefineDataset() {
            object[] results = this.Invoke("fnDefineDataset", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfnDefineDataset(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("fnDefineDataset", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndfnDefineDataset(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void fnDefineDatasetAsync() {
            this.fnDefineDatasetAsync(null);
        }
        
        /// <remarks/>
        public void fnDefineDatasetAsync(object userState) {
            if ((this.fnDefineDatasetOperationCompleted == null)) {
                this.fnDefineDatasetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfnDefineDatasetOperationCompleted);
            }
            this.InvokeAsync("fnDefineDataset", new object[0], this.fnDefineDatasetOperationCompleted, userState);
        }
        
        private void OnfnDefineDatasetOperationCompleted(object arg) {
            if ((this.fnDefineDatasetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fnDefineDatasetCompleted(this, new fnDefineDatasetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fnNovoNumero", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int fnNovoNumero() {
            object[] results = this.Invoke("fnNovoNumero", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfnNovoNumero(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("fnNovoNumero", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public int EndfnNovoNumero(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void fnNovoNumeroAsync() {
            this.fnNovoNumeroAsync(null);
        }
        
        /// <remarks/>
        public void fnNovoNumeroAsync(object userState) {
            if ((this.fnNovoNumeroOperationCompleted == null)) {
                this.fnNovoNumeroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfnNovoNumeroOperationCompleted);
            }
            this.InvokeAsync("fnNovoNumero", new object[0], this.fnNovoNumeroOperationCompleted, userState);
        }
        
        private void OnfnNovoNumeroOperationCompleted(object arg) {
            if ((this.fnNovoNumeroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fnNovoNumeroCompleted(this, new fnNovoNumeroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fnCarregaGrade", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet fnCarregaGrade(System.DateTime pDataInicio, System.DateTime pDataFim, string pCodVeiculo) {
            object[] results = this.Invoke("fnCarregaGrade", new object[] {
                        pDataInicio,
                        pDataFim,
                        pCodVeiculo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfnCarregaGrade(System.DateTime pDataInicio, System.DateTime pDataFim, string pCodVeiculo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("fnCarregaGrade", new object[] {
                        pDataInicio,
                        pDataFim,
                        pCodVeiculo}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndfnCarregaGrade(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void fnCarregaGradeAsync(System.DateTime pDataInicio, System.DateTime pDataFim, string pCodVeiculo) {
            this.fnCarregaGradeAsync(pDataInicio, pDataFim, pCodVeiculo, null);
        }
        
        /// <remarks/>
        public void fnCarregaGradeAsync(System.DateTime pDataInicio, System.DateTime pDataFim, string pCodVeiculo, object userState) {
            if ((this.fnCarregaGradeOperationCompleted == null)) {
                this.fnCarregaGradeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfnCarregaGradeOperationCompleted);
            }
            this.InvokeAsync("fnCarregaGrade", new object[] {
                        pDataInicio,
                        pDataFim,
                        pCodVeiculo}, this.fnCarregaGradeOperationCompleted, userState);
        }
        
        private void OnfnCarregaGradeOperationCompleted(object arg) {
            if ((this.fnCarregaGradeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fnCarregaGradeCompleted(this, new fnCarregaGradeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fnVeiculoUsuarioCarregar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet fnVeiculoUsuarioCarregar(string pUsuario) {
            object[] results = this.Invoke("fnVeiculoUsuarioCarregar", new object[] {
                        pUsuario});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfnVeiculoUsuarioCarregar(string pUsuario, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("fnVeiculoUsuarioCarregar", new object[] {
                        pUsuario}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndfnVeiculoUsuarioCarregar(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void fnVeiculoUsuarioCarregarAsync(string pUsuario) {
            this.fnVeiculoUsuarioCarregarAsync(pUsuario, null);
        }
        
        /// <remarks/>
        public void fnVeiculoUsuarioCarregarAsync(string pUsuario, object userState) {
            if ((this.fnVeiculoUsuarioCarregarOperationCompleted == null)) {
                this.fnVeiculoUsuarioCarregarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfnVeiculoUsuarioCarregarOperationCompleted);
            }
            this.InvokeAsync("fnVeiculoUsuarioCarregar", new object[] {
                        pUsuario}, this.fnVeiculoUsuarioCarregarOperationCompleted, userState);
        }
        
        private void OnfnVeiculoUsuarioCarregarOperationCompleted(object arg) {
            if ((this.fnVeiculoUsuarioCarregarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fnVeiculoUsuarioCarregarCompleted(this, new fnVeiculoUsuarioCarregarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fnConsisteCaracteristicaVeiculacao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool fnConsisteCaracteristicaVeiculacao(string pCodigo) {
            object[] results = this.Invoke("fnConsisteCaracteristicaVeiculacao", new object[] {
                        pCodigo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfnConsisteCaracteristicaVeiculacao(string pCodigo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("fnConsisteCaracteristicaVeiculacao", new object[] {
                        pCodigo}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndfnConsisteCaracteristicaVeiculacao(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void fnConsisteCaracteristicaVeiculacaoAsync(string pCodigo) {
            this.fnConsisteCaracteristicaVeiculacaoAsync(pCodigo, null);
        }
        
        /// <remarks/>
        public void fnConsisteCaracteristicaVeiculacaoAsync(string pCodigo, object userState) {
            if ((this.fnConsisteCaracteristicaVeiculacaoOperationCompleted == null)) {
                this.fnConsisteCaracteristicaVeiculacaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfnConsisteCaracteristicaVeiculacaoOperationCompleted);
            }
            this.InvokeAsync("fnConsisteCaracteristicaVeiculacao", new object[] {
                        pCodigo}, this.fnConsisteCaracteristicaVeiculacaoOperationCompleted, userState);
        }
        
        private void OnfnConsisteCaracteristicaVeiculacaoOperationCompleted(object arg) {
            if ((this.fnConsisteCaracteristicaVeiculacaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fnConsisteCaracteristicaVeiculacaoCompleted(this, new fnConsisteCaracteristicaVeiculacaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fnCriaNegociacao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object fnCriaNegociacao(int pCompetencia, string pCod_Empresa, string pCod_Empresa_Faturamento, string pCod_Agencia, string pCod_Cliente, string pCod_Nucleo, string pCod_Contato, string pcod_Tipo_Midia, string pCod_Usuario) {
            object[] results = this.Invoke("fnCriaNegociacao", new object[] {
                        pCompetencia,
                        pCod_Empresa,
                        pCod_Empresa_Faturamento,
                        pCod_Agencia,
                        pCod_Cliente,
                        pCod_Nucleo,
                        pCod_Contato,
                        pcod_Tipo_Midia,
                        pCod_Usuario});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfnCriaNegociacao(int pCompetencia, string pCod_Empresa, string pCod_Empresa_Faturamento, string pCod_Agencia, string pCod_Cliente, string pCod_Nucleo, string pCod_Contato, string pcod_Tipo_Midia, string pCod_Usuario, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("fnCriaNegociacao", new object[] {
                        pCompetencia,
                        pCod_Empresa,
                        pCod_Empresa_Faturamento,
                        pCod_Agencia,
                        pCod_Cliente,
                        pCod_Nucleo,
                        pCod_Contato,
                        pcod_Tipo_Midia,
                        pCod_Usuario}, callback, asyncState);
        }
        
        /// <remarks/>
        public object EndfnCriaNegociacao(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void fnCriaNegociacaoAsync(int pCompetencia, string pCod_Empresa, string pCod_Empresa_Faturamento, string pCod_Agencia, string pCod_Cliente, string pCod_Nucleo, string pCod_Contato, string pcod_Tipo_Midia, string pCod_Usuario) {
            this.fnCriaNegociacaoAsync(pCompetencia, pCod_Empresa, pCod_Empresa_Faturamento, pCod_Agencia, pCod_Cliente, pCod_Nucleo, pCod_Contato, pcod_Tipo_Midia, pCod_Usuario, null);
        }
        
        /// <remarks/>
        public void fnCriaNegociacaoAsync(int pCompetencia, string pCod_Empresa, string pCod_Empresa_Faturamento, string pCod_Agencia, string pCod_Cliente, string pCod_Nucleo, string pCod_Contato, string pcod_Tipo_Midia, string pCod_Usuario, object userState) {
            if ((this.fnCriaNegociacaoOperationCompleted == null)) {
                this.fnCriaNegociacaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfnCriaNegociacaoOperationCompleted);
            }
            this.InvokeAsync("fnCriaNegociacao", new object[] {
                        pCompetencia,
                        pCod_Empresa,
                        pCod_Empresa_Faturamento,
                        pCod_Agencia,
                        pCod_Cliente,
                        pCod_Nucleo,
                        pCod_Contato,
                        pcod_Tipo_Midia,
                        pCod_Usuario}, this.fnCriaNegociacaoOperationCompleted, userState);
        }
        
        private void OnfnCriaNegociacaoOperationCompleted(object arg) {
            if ((this.fnCriaNegociacaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fnCriaNegociacaoCompleted(this, new fnCriaNegociacaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FnSalvar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet FnSalvar(System.Data.DataSet dtsContrato, System.Data.DataSet dtsVeiculo, string pUsuario) {
            object[] results = this.Invoke("FnSalvar", new object[] {
                        dtsContrato,
                        dtsVeiculo,
                        pUsuario});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginFnSalvar(System.Data.DataSet dtsContrato, System.Data.DataSet dtsVeiculo, string pUsuario, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FnSalvar", new object[] {
                        dtsContrato,
                        dtsVeiculo,
                        pUsuario}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndFnSalvar(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void FnSalvarAsync(System.Data.DataSet dtsContrato, System.Data.DataSet dtsVeiculo, string pUsuario) {
            this.FnSalvarAsync(dtsContrato, dtsVeiculo, pUsuario, null);
        }
        
        /// <remarks/>
        public void FnSalvarAsync(System.Data.DataSet dtsContrato, System.Data.DataSet dtsVeiculo, string pUsuario, object userState) {
            if ((this.FnSalvarOperationCompleted == null)) {
                this.FnSalvarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFnSalvarOperationCompleted);
            }
            this.InvokeAsync("FnSalvar", new object[] {
                        dtsContrato,
                        dtsVeiculo,
                        pUsuario}, this.FnSalvarOperationCompleted, userState);
        }
        
        private void OnFnSalvarOperationCompleted(object arg) {
            if ((this.FnSalvarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FnSalvarCompleted(this, new FnSalvarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fnIem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool fnIem(string pCodEmpresa, int pNumeroMr, short pSequenciaMr, int pCompetencia, System.Data.DataSet dtsVeiculo) {
            object[] results = this.Invoke("fnIem", new object[] {
                        pCodEmpresa,
                        pNumeroMr,
                        pSequenciaMr,
                        pCompetencia,
                        dtsVeiculo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfnIem(string pCodEmpresa, int pNumeroMr, short pSequenciaMr, int pCompetencia, System.Data.DataSet dtsVeiculo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("fnIem", new object[] {
                        pCodEmpresa,
                        pNumeroMr,
                        pSequenciaMr,
                        pCompetencia,
                        dtsVeiculo}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndfnIem(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void fnIemAsync(string pCodEmpresa, int pNumeroMr, short pSequenciaMr, int pCompetencia, System.Data.DataSet dtsVeiculo) {
            this.fnIemAsync(pCodEmpresa, pNumeroMr, pSequenciaMr, pCompetencia, dtsVeiculo, null);
        }
        
        /// <remarks/>
        public void fnIemAsync(string pCodEmpresa, int pNumeroMr, short pSequenciaMr, int pCompetencia, System.Data.DataSet dtsVeiculo, object userState) {
            if ((this.fnIemOperationCompleted == null)) {
                this.fnIemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfnIemOperationCompleted);
            }
            this.InvokeAsync("fnIem", new object[] {
                        pCodEmpresa,
                        pNumeroMr,
                        pSequenciaMr,
                        pCompetencia,
                        dtsVeiculo}, this.fnIemOperationCompleted, userState);
        }
        
        private void OnfnIemOperationCompleted(object arg) {
            if ((this.fnIemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fnIemCompleted(this, new fnIemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fnReabreCE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string fnReabreCE(string pCodEmpresa, int pNumeroMr, short pSequenciaMr, string pVeiculo, string pMotivo) {
            object[] results = this.Invoke("fnReabreCE", new object[] {
                        pCodEmpresa,
                        pNumeroMr,
                        pSequenciaMr,
                        pVeiculo,
                        pMotivo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfnReabreCE(string pCodEmpresa, int pNumeroMr, short pSequenciaMr, string pVeiculo, string pMotivo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("fnReabreCE", new object[] {
                        pCodEmpresa,
                        pNumeroMr,
                        pSequenciaMr,
                        pVeiculo,
                        pMotivo}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndfnReabreCE(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void fnReabreCEAsync(string pCodEmpresa, int pNumeroMr, short pSequenciaMr, string pVeiculo, string pMotivo) {
            this.fnReabreCEAsync(pCodEmpresa, pNumeroMr, pSequenciaMr, pVeiculo, pMotivo, null);
        }
        
        /// <remarks/>
        public void fnReabreCEAsync(string pCodEmpresa, int pNumeroMr, short pSequenciaMr, string pVeiculo, string pMotivo, object userState) {
            if ((this.fnReabreCEOperationCompleted == null)) {
                this.fnReabreCEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfnReabreCEOperationCompleted);
            }
            this.InvokeAsync("fnReabreCE", new object[] {
                        pCodEmpresa,
                        pNumeroMr,
                        pSequenciaMr,
                        pVeiculo,
                        pMotivo}, this.fnReabreCEOperationCompleted, userState);
        }
        
        private void OnfnReabreCEOperationCompleted(object arg) {
            if ((this.fnReabreCECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fnReabreCECompleted(this, new fnReabreCECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fnIEV", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool fnIEV(string pCod_Empresa, int pNumero_Mr, short pSequenciaMr, string pCod_Usuario, short pMotivoAlteracao) {
            object[] results = this.Invoke("fnIEV", new object[] {
                        pCod_Empresa,
                        pNumero_Mr,
                        pSequenciaMr,
                        pCod_Usuario,
                        pMotivoAlteracao});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfnIEV(string pCod_Empresa, int pNumero_Mr, short pSequenciaMr, string pCod_Usuario, short pMotivoAlteracao, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("fnIEV", new object[] {
                        pCod_Empresa,
                        pNumero_Mr,
                        pSequenciaMr,
                        pCod_Usuario,
                        pMotivoAlteracao}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndfnIEV(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void fnIEVAsync(string pCod_Empresa, int pNumero_Mr, short pSequenciaMr, string pCod_Usuario, short pMotivoAlteracao) {
            this.fnIEVAsync(pCod_Empresa, pNumero_Mr, pSequenciaMr, pCod_Usuario, pMotivoAlteracao, null);
        }
        
        /// <remarks/>
        public void fnIEVAsync(string pCod_Empresa, int pNumero_Mr, short pSequenciaMr, string pCod_Usuario, short pMotivoAlteracao, object userState) {
            if ((this.fnIEVOperationCompleted == null)) {
                this.fnIEVOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfnIEVOperationCompleted);
            }
            this.InvokeAsync("fnIEV", new object[] {
                        pCod_Empresa,
                        pNumero_Mr,
                        pSequenciaMr,
                        pCod_Usuario,
                        pMotivoAlteracao}, this.fnIEVOperationCompleted, userState);
        }
        
        private void OnfnIEVOperationCompleted(object arg) {
            if ((this.fnIEVCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fnIEVCompleted(this, new fnIEVCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fnExisteMr", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool fnExisteMr(string pCodEmpresa, int pNumeroMr, short pSequenciaMr) {
            object[] results = this.Invoke("fnExisteMr", new object[] {
                        pCodEmpresa,
                        pNumeroMr,
                        pSequenciaMr});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfnExisteMr(string pCodEmpresa, int pNumeroMr, short pSequenciaMr, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("fnExisteMr", new object[] {
                        pCodEmpresa,
                        pNumeroMr,
                        pSequenciaMr}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndfnExisteMr(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void fnExisteMrAsync(string pCodEmpresa, int pNumeroMr, short pSequenciaMr) {
            this.fnExisteMrAsync(pCodEmpresa, pNumeroMr, pSequenciaMr, null);
        }
        
        /// <remarks/>
        public void fnExisteMrAsync(string pCodEmpresa, int pNumeroMr, short pSequenciaMr, object userState) {
            if ((this.fnExisteMrOperationCompleted == null)) {
                this.fnExisteMrOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfnExisteMrOperationCompleted);
            }
            this.InvokeAsync("fnExisteMr", new object[] {
                        pCodEmpresa,
                        pNumeroMr,
                        pSequenciaMr}, this.fnExisteMrOperationCompleted, userState);
        }
        
        private void OnfnExisteMrOperationCompleted(object arg) {
            if ((this.fnExisteMrCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fnExisteMrCompleted(this, new fnExisteMrCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fnUltimaSequencia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public short fnUltimaSequencia(string pCodEmpresa, int pNumeroMr) {
            object[] results = this.Invoke("fnUltimaSequencia", new object[] {
                        pCodEmpresa,
                        pNumeroMr});
            return ((short)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfnUltimaSequencia(string pCodEmpresa, int pNumeroMr, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("fnUltimaSequencia", new object[] {
                        pCodEmpresa,
                        pNumeroMr}, callback, asyncState);
        }
        
        /// <remarks/>
        public short EndfnUltimaSequencia(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((short)(results[0]));
        }
        
        /// <remarks/>
        public void fnUltimaSequenciaAsync(string pCodEmpresa, int pNumeroMr) {
            this.fnUltimaSequenciaAsync(pCodEmpresa, pNumeroMr, null);
        }
        
        /// <remarks/>
        public void fnUltimaSequenciaAsync(string pCodEmpresa, int pNumeroMr, object userState) {
            if ((this.fnUltimaSequenciaOperationCompleted == null)) {
                this.fnUltimaSequenciaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfnUltimaSequenciaOperationCompleted);
            }
            this.InvokeAsync("fnUltimaSequencia", new object[] {
                        pCodEmpresa,
                        pNumeroMr}, this.fnUltimaSequenciaOperationCompleted, userState);
        }
        
        private void OnfnUltimaSequenciaOperationCompleted(object arg) {
            if ((this.fnUltimaSequenciaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fnUltimaSequenciaCompleted(this, new fnUltimaSequenciaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fnCarregaContrato", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet fnCarregaContrato(string pCodEmpresa, int pNumeroMr, short pSequenciaMr) {
            object[] results = this.Invoke("fnCarregaContrato", new object[] {
                        pCodEmpresa,
                        pNumeroMr,
                        pSequenciaMr});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfnCarregaContrato(string pCodEmpresa, int pNumeroMr, short pSequenciaMr, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("fnCarregaContrato", new object[] {
                        pCodEmpresa,
                        pNumeroMr,
                        pSequenciaMr}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndfnCarregaContrato(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void fnCarregaContratoAsync(string pCodEmpresa, int pNumeroMr, short pSequenciaMr) {
            this.fnCarregaContratoAsync(pCodEmpresa, pNumeroMr, pSequenciaMr, null);
        }
        
        /// <remarks/>
        public void fnCarregaContratoAsync(string pCodEmpresa, int pNumeroMr, short pSequenciaMr, object userState) {
            if ((this.fnCarregaContratoOperationCompleted == null)) {
                this.fnCarregaContratoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfnCarregaContratoOperationCompleted);
            }
            this.InvokeAsync("fnCarregaContrato", new object[] {
                        pCodEmpresa,
                        pNumeroMr,
                        pSequenciaMr}, this.fnCarregaContratoOperationCompleted, userState);
        }
        
        private void OnfnCarregaContratoOperationCompleted(object arg) {
            if ((this.fnCarregaContratoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fnCarregaContratoCompleted(this, new fnCarregaContratoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fnDeterminacao_Dados_Contrato", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet fnDeterminacao_Dados_Contrato(string pCod_Empresa, int pContrato, short pSeq) {
            object[] results = this.Invoke("fnDeterminacao_Dados_Contrato", new object[] {
                        pCod_Empresa,
                        pContrato,
                        pSeq});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfnDeterminacao_Dados_Contrato(string pCod_Empresa, int pContrato, short pSeq, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("fnDeterminacao_Dados_Contrato", new object[] {
                        pCod_Empresa,
                        pContrato,
                        pSeq}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndfnDeterminacao_Dados_Contrato(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void fnDeterminacao_Dados_ContratoAsync(string pCod_Empresa, int pContrato, short pSeq) {
            this.fnDeterminacao_Dados_ContratoAsync(pCod_Empresa, pContrato, pSeq, null);
        }
        
        /// <remarks/>
        public void fnDeterminacao_Dados_ContratoAsync(string pCod_Empresa, int pContrato, short pSeq, object userState) {
            if ((this.fnDeterminacao_Dados_ContratoOperationCompleted == null)) {
                this.fnDeterminacao_Dados_ContratoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfnDeterminacao_Dados_ContratoOperationCompleted);
            }
            this.InvokeAsync("fnDeterminacao_Dados_Contrato", new object[] {
                        pCod_Empresa,
                        pContrato,
                        pSeq}, this.fnDeterminacao_Dados_ContratoOperationCompleted, userState);
        }
        
        private void OnfnDeterminacao_Dados_ContratoOperationCompleted(object arg) {
            if ((this.fnDeterminacao_Dados_ContratoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fnDeterminacao_Dados_ContratoCompleted(this, new fnDeterminacao_Dados_ContratoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fnDeterminacao_Dados_Comercial", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet fnDeterminacao_Dados_Comercial(string pCod_Empresa, int pContrato, short pSeq) {
            object[] results = this.Invoke("fnDeterminacao_Dados_Comercial", new object[] {
                        pCod_Empresa,
                        pContrato,
                        pSeq});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfnDeterminacao_Dados_Comercial(string pCod_Empresa, int pContrato, short pSeq, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("fnDeterminacao_Dados_Comercial", new object[] {
                        pCod_Empresa,
                        pContrato,
                        pSeq}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndfnDeterminacao_Dados_Comercial(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void fnDeterminacao_Dados_ComercialAsync(string pCod_Empresa, int pContrato, short pSeq) {
            this.fnDeterminacao_Dados_ComercialAsync(pCod_Empresa, pContrato, pSeq, null);
        }
        
        /// <remarks/>
        public void fnDeterminacao_Dados_ComercialAsync(string pCod_Empresa, int pContrato, short pSeq, object userState) {
            if ((this.fnDeterminacao_Dados_ComercialOperationCompleted == null)) {
                this.fnDeterminacao_Dados_ComercialOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfnDeterminacao_Dados_ComercialOperationCompleted);
            }
            this.InvokeAsync("fnDeterminacao_Dados_Comercial", new object[] {
                        pCod_Empresa,
                        pContrato,
                        pSeq}, this.fnDeterminacao_Dados_ComercialOperationCompleted, userState);
        }
        
        private void OnfnDeterminacao_Dados_ComercialOperationCompleted(object arg) {
            if ((this.fnDeterminacao_Dados_ComercialCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fnDeterminacao_Dados_ComercialCompleted(this, new fnDeterminacao_Dados_ComercialCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fnDeterminacao_Select", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet fnDeterminacao_Select(string pCod_Empresa, int pContrato, short pSeq, string pCod_Veiculo, System.DateTime pDataInicio, System.DateTime pDataFim) {
            object[] results = this.Invoke("fnDeterminacao_Select", new object[] {
                        pCod_Empresa,
                        pContrato,
                        pSeq,
                        pCod_Veiculo,
                        pDataInicio,
                        pDataFim});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfnDeterminacao_Select(string pCod_Empresa, int pContrato, short pSeq, string pCod_Veiculo, System.DateTime pDataInicio, System.DateTime pDataFim, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("fnDeterminacao_Select", new object[] {
                        pCod_Empresa,
                        pContrato,
                        pSeq,
                        pCod_Veiculo,
                        pDataInicio,
                        pDataFim}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndfnDeterminacao_Select(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void fnDeterminacao_SelectAsync(string pCod_Empresa, int pContrato, short pSeq, string pCod_Veiculo, System.DateTime pDataInicio, System.DateTime pDataFim) {
            this.fnDeterminacao_SelectAsync(pCod_Empresa, pContrato, pSeq, pCod_Veiculo, pDataInicio, pDataFim, null);
        }
        
        /// <remarks/>
        public void fnDeterminacao_SelectAsync(string pCod_Empresa, int pContrato, short pSeq, string pCod_Veiculo, System.DateTime pDataInicio, System.DateTime pDataFim, object userState) {
            if ((this.fnDeterminacao_SelectOperationCompleted == null)) {
                this.fnDeterminacao_SelectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfnDeterminacao_SelectOperationCompleted);
            }
            this.InvokeAsync("fnDeterminacao_Select", new object[] {
                        pCod_Empresa,
                        pContrato,
                        pSeq,
                        pCod_Veiculo,
                        pDataInicio,
                        pDataFim}, this.fnDeterminacao_SelectOperationCompleted, userState);
        }
        
        private void OnfnDeterminacao_SelectOperationCompleted(object arg) {
            if ((this.fnDeterminacao_SelectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fnDeterminacao_SelectCompleted(this, new fnDeterminacao_SelectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fnDeterminacaoPendente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet fnDeterminacaoPendente(System.DateTime pDataInicio, System.DateTime pDataFim, string pCodVeiculo, string pUsuario) {
            object[] results = this.Invoke("fnDeterminacaoPendente", new object[] {
                        pDataInicio,
                        pDataFim,
                        pCodVeiculo,
                        pUsuario});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfnDeterminacaoPendente(System.DateTime pDataInicio, System.DateTime pDataFim, string pCodVeiculo, string pUsuario, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("fnDeterminacaoPendente", new object[] {
                        pDataInicio,
                        pDataFim,
                        pCodVeiculo,
                        pUsuario}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndfnDeterminacaoPendente(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void fnDeterminacaoPendenteAsync(System.DateTime pDataInicio, System.DateTime pDataFim, string pCodVeiculo, string pUsuario) {
            this.fnDeterminacaoPendenteAsync(pDataInicio, pDataFim, pCodVeiculo, pUsuario, null);
        }
        
        /// <remarks/>
        public void fnDeterminacaoPendenteAsync(System.DateTime pDataInicio, System.DateTime pDataFim, string pCodVeiculo, string pUsuario, object userState) {
            if ((this.fnDeterminacaoPendenteOperationCompleted == null)) {
                this.fnDeterminacaoPendenteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfnDeterminacaoPendenteOperationCompleted);
            }
            this.InvokeAsync("fnDeterminacaoPendente", new object[] {
                        pDataInicio,
                        pDataFim,
                        pCodVeiculo,
                        pUsuario}, this.fnDeterminacaoPendenteOperationCompleted, userState);
        }
        
        private void OnfnDeterminacaoPendenteOperationCompleted(object arg) {
            if ((this.fnDeterminacaoPendenteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fnDeterminacaoPendenteCompleted(this, new fnDeterminacaoPendenteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fnDeterminacao_Veiculo_Select", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet fnDeterminacao_Veiculo_Select(string pCod_Empresa, int pContrato, short pSeq) {
            object[] results = this.Invoke("fnDeterminacao_Veiculo_Select", new object[] {
                        pCod_Empresa,
                        pContrato,
                        pSeq});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfnDeterminacao_Veiculo_Select(string pCod_Empresa, int pContrato, short pSeq, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("fnDeterminacao_Veiculo_Select", new object[] {
                        pCod_Empresa,
                        pContrato,
                        pSeq}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndfnDeterminacao_Veiculo_Select(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void fnDeterminacao_Veiculo_SelectAsync(string pCod_Empresa, int pContrato, short pSeq) {
            this.fnDeterminacao_Veiculo_SelectAsync(pCod_Empresa, pContrato, pSeq, null);
        }
        
        /// <remarks/>
        public void fnDeterminacao_Veiculo_SelectAsync(string pCod_Empresa, int pContrato, short pSeq, object userState) {
            if ((this.fnDeterminacao_Veiculo_SelectOperationCompleted == null)) {
                this.fnDeterminacao_Veiculo_SelectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfnDeterminacao_Veiculo_SelectOperationCompleted);
            }
            this.InvokeAsync("fnDeterminacao_Veiculo_Select", new object[] {
                        pCod_Empresa,
                        pContrato,
                        pSeq}, this.fnDeterminacao_Veiculo_SelectOperationCompleted, userState);
        }
        
        private void OnfnDeterminacao_Veiculo_SelectOperationCompleted(object arg) {
            if ((this.fnDeterminacao_Veiculo_SelectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fnDeterminacao_Veiculo_SelectCompleted(this, new fnDeterminacao_Veiculo_SelectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fnDeterminacao_Delete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void fnDeterminacao_Delete(string pCod_Empresa, int pContrato, short pSeq, string pUsuario) {
            this.Invoke("fnDeterminacao_Delete", new object[] {
                        pCod_Empresa,
                        pContrato,
                        pSeq,
                        pUsuario});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfnDeterminacao_Delete(string pCod_Empresa, int pContrato, short pSeq, string pUsuario, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("fnDeterminacao_Delete", new object[] {
                        pCod_Empresa,
                        pContrato,
                        pSeq,
                        pUsuario}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndfnDeterminacao_Delete(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void fnDeterminacao_DeleteAsync(string pCod_Empresa, int pContrato, short pSeq, string pUsuario) {
            this.fnDeterminacao_DeleteAsync(pCod_Empresa, pContrato, pSeq, pUsuario, null);
        }
        
        /// <remarks/>
        public void fnDeterminacao_DeleteAsync(string pCod_Empresa, int pContrato, short pSeq, string pUsuario, object userState) {
            if ((this.fnDeterminacao_DeleteOperationCompleted == null)) {
                this.fnDeterminacao_DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfnDeterminacao_DeleteOperationCompleted);
            }
            this.InvokeAsync("fnDeterminacao_Delete", new object[] {
                        pCod_Empresa,
                        pContrato,
                        pSeq,
                        pUsuario}, this.fnDeterminacao_DeleteOperationCompleted, userState);
        }
        
        private void OnfnDeterminacao_DeleteOperationCompleted(object arg) {
            if ((this.fnDeterminacao_DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fnDeterminacao_DeleteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fnDeterminacao_Insert", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void fnDeterminacao_Insert(string pCod_Empresa, int pContrato, short pSeq, string pCodVeiculo, System.DateTime pDataExibicao, string pCodPrograma, int pChaveAcesso, string pCodComercial, byte pIndicaBaixa, byte pIndicaInclusao, string pUsuario, byte pIndicaBaixado) {
            this.Invoke("fnDeterminacao_Insert", new object[] {
                        pCod_Empresa,
                        pContrato,
                        pSeq,
                        pCodVeiculo,
                        pDataExibicao,
                        pCodPrograma,
                        pChaveAcesso,
                        pCodComercial,
                        pIndicaBaixa,
                        pIndicaInclusao,
                        pUsuario,
                        pIndicaBaixado});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfnDeterminacao_Insert(string pCod_Empresa, int pContrato, short pSeq, string pCodVeiculo, System.DateTime pDataExibicao, string pCodPrograma, int pChaveAcesso, string pCodComercial, byte pIndicaBaixa, byte pIndicaInclusao, string pUsuario, byte pIndicaBaixado, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("fnDeterminacao_Insert", new object[] {
                        pCod_Empresa,
                        pContrato,
                        pSeq,
                        pCodVeiculo,
                        pDataExibicao,
                        pCodPrograma,
                        pChaveAcesso,
                        pCodComercial,
                        pIndicaBaixa,
                        pIndicaInclusao,
                        pUsuario,
                        pIndicaBaixado}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndfnDeterminacao_Insert(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void fnDeterminacao_InsertAsync(string pCod_Empresa, int pContrato, short pSeq, string pCodVeiculo, System.DateTime pDataExibicao, string pCodPrograma, int pChaveAcesso, string pCodComercial, byte pIndicaBaixa, byte pIndicaInclusao, string pUsuario, byte pIndicaBaixado) {
            this.fnDeterminacao_InsertAsync(pCod_Empresa, pContrato, pSeq, pCodVeiculo, pDataExibicao, pCodPrograma, pChaveAcesso, pCodComercial, pIndicaBaixa, pIndicaInclusao, pUsuario, pIndicaBaixado, null);
        }
        
        /// <remarks/>
        public void fnDeterminacao_InsertAsync(string pCod_Empresa, int pContrato, short pSeq, string pCodVeiculo, System.DateTime pDataExibicao, string pCodPrograma, int pChaveAcesso, string pCodComercial, byte pIndicaBaixa, byte pIndicaInclusao, string pUsuario, byte pIndicaBaixado, object userState) {
            if ((this.fnDeterminacao_InsertOperationCompleted == null)) {
                this.fnDeterminacao_InsertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfnDeterminacao_InsertOperationCompleted);
            }
            this.InvokeAsync("fnDeterminacao_Insert", new object[] {
                        pCod_Empresa,
                        pContrato,
                        pSeq,
                        pCodVeiculo,
                        pDataExibicao,
                        pCodPrograma,
                        pChaveAcesso,
                        pCodComercial,
                        pIndicaBaixa,
                        pIndicaInclusao,
                        pUsuario,
                        pIndicaBaixado}, this.fnDeterminacao_InsertOperationCompleted, userState);
        }
        
        private void OnfnDeterminacao_InsertOperationCompleted(object arg) {
            if ((this.fnDeterminacao_InsertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fnDeterminacao_InsertCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fnDeterminacao_Comerciais", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string fnDeterminacao_Comerciais(string pCod_Empresa, int pContrato, short pSeq, string pCod_Usuario) {
            object[] results = this.Invoke("fnDeterminacao_Comerciais", new object[] {
                        pCod_Empresa,
                        pContrato,
                        pSeq,
                        pCod_Usuario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfnDeterminacao_Comerciais(string pCod_Empresa, int pContrato, short pSeq, string pCod_Usuario, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("fnDeterminacao_Comerciais", new object[] {
                        pCod_Empresa,
                        pContrato,
                        pSeq,
                        pCod_Usuario}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndfnDeterminacao_Comerciais(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void fnDeterminacao_ComerciaisAsync(string pCod_Empresa, int pContrato, short pSeq, string pCod_Usuario) {
            this.fnDeterminacao_ComerciaisAsync(pCod_Empresa, pContrato, pSeq, pCod_Usuario, null);
        }
        
        /// <remarks/>
        public void fnDeterminacao_ComerciaisAsync(string pCod_Empresa, int pContrato, short pSeq, string pCod_Usuario, object userState) {
            if ((this.fnDeterminacao_ComerciaisOperationCompleted == null)) {
                this.fnDeterminacao_ComerciaisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfnDeterminacao_ComerciaisOperationCompleted);
            }
            this.InvokeAsync("fnDeterminacao_Comerciais", new object[] {
                        pCod_Empresa,
                        pContrato,
                        pSeq,
                        pCod_Usuario}, this.fnDeterminacao_ComerciaisOperationCompleted, userState);
        }
        
        private void OnfnDeterminacao_ComerciaisOperationCompleted(object arg) {
            if ((this.fnDeterminacao_ComerciaisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fnDeterminacao_ComerciaisCompleted(this, new fnDeterminacao_ComerciaisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fnExisteComercial", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool fnExisteComercial(string pCod_Empresa, int pContrato, int pSeq, string pCod_Comercial) {
            object[] results = this.Invoke("fnExisteComercial", new object[] {
                        pCod_Empresa,
                        pContrato,
                        pSeq,
                        pCod_Comercial});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfnExisteComercial(string pCod_Empresa, int pContrato, int pSeq, string pCod_Comercial, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("fnExisteComercial", new object[] {
                        pCod_Empresa,
                        pContrato,
                        pSeq,
                        pCod_Comercial}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndfnExisteComercial(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void fnExisteComercialAsync(string pCod_Empresa, int pContrato, int pSeq, string pCod_Comercial) {
            this.fnExisteComercialAsync(pCod_Empresa, pContrato, pSeq, pCod_Comercial, null);
        }
        
        /// <remarks/>
        public void fnExisteComercialAsync(string pCod_Empresa, int pContrato, int pSeq, string pCod_Comercial, object userState) {
            if ((this.fnExisteComercialOperationCompleted == null)) {
                this.fnExisteComercialOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfnExisteComercialOperationCompleted);
            }
            this.InvokeAsync("fnExisteComercial", new object[] {
                        pCod_Empresa,
                        pContrato,
                        pSeq,
                        pCod_Comercial}, this.fnExisteComercialOperationCompleted, userState);
        }
        
        private void OnfnExisteComercialOperationCompleted(object arg) {
            if ((this.fnExisteComercialCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fnExisteComercialCompleted(this, new fnExisteComercialCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fnExcluirComercial", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool fnExcluirComercial(string pCod_Empresa, int pContrato, int pSeq, string pCod_Comercial) {
            object[] results = this.Invoke("fnExcluirComercial", new object[] {
                        pCod_Empresa,
                        pContrato,
                        pSeq,
                        pCod_Comercial});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfnExcluirComercial(string pCod_Empresa, int pContrato, int pSeq, string pCod_Comercial, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("fnExcluirComercial", new object[] {
                        pCod_Empresa,
                        pContrato,
                        pSeq,
                        pCod_Comercial}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndfnExcluirComercial(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void fnExcluirComercialAsync(string pCod_Empresa, int pContrato, int pSeq, string pCod_Comercial) {
            this.fnExcluirComercialAsync(pCod_Empresa, pContrato, pSeq, pCod_Comercial, null);
        }
        
        /// <remarks/>
        public void fnExcluirComercialAsync(string pCod_Empresa, int pContrato, int pSeq, string pCod_Comercial, object userState) {
            if ((this.fnExcluirComercialOperationCompleted == null)) {
                this.fnExcluirComercialOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfnExcluirComercialOperationCompleted);
            }
            this.InvokeAsync("fnExcluirComercial", new object[] {
                        pCod_Empresa,
                        pContrato,
                        pSeq,
                        pCod_Comercial}, this.fnExcluirComercialOperationCompleted, userState);
        }
        
        private void OnfnExcluirComercialOperationCompleted(object arg) {
            if ((this.fnExcluirComercialCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fnExcluirComercialCompleted(this, new fnExcluirComercialCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class AuthSoapHd : System.Web.Services.Protocols.SoapHeader {
        
        private string strUserNameField;
        
        private string strPasswordField;
        
        private string strKeyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string strUserName {
            get {
                return this.strUserNameField;
            }
            set {
                this.strUserNameField = value;
            }
        }
        
        /// <remarks/>
        public string strPassword {
            get {
                return this.strPasswordField;
            }
            set {
                this.strPasswordField = value;
            }
        }
        
        /// <remarks/>
        public string strKey {
            get {
                return this.strKeyField;
            }
            set {
                this.strKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void fnDefineDatasetCompletedEventHandler(object sender, fnDefineDatasetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fnDefineDatasetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fnDefineDatasetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void fnNovoNumeroCompletedEventHandler(object sender, fnNovoNumeroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fnNovoNumeroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fnNovoNumeroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void fnCarregaGradeCompletedEventHandler(object sender, fnCarregaGradeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fnCarregaGradeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fnCarregaGradeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void fnVeiculoUsuarioCarregarCompletedEventHandler(object sender, fnVeiculoUsuarioCarregarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fnVeiculoUsuarioCarregarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fnVeiculoUsuarioCarregarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void fnConsisteCaracteristicaVeiculacaoCompletedEventHandler(object sender, fnConsisteCaracteristicaVeiculacaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fnConsisteCaracteristicaVeiculacaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fnConsisteCaracteristicaVeiculacaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void fnCriaNegociacaoCompletedEventHandler(object sender, fnCriaNegociacaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fnCriaNegociacaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fnCriaNegociacaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void FnSalvarCompletedEventHandler(object sender, FnSalvarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FnSalvarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FnSalvarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void fnIemCompletedEventHandler(object sender, fnIemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fnIemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fnIemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void fnReabreCECompletedEventHandler(object sender, fnReabreCECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fnReabreCECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fnReabreCECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void fnIEVCompletedEventHandler(object sender, fnIEVCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fnIEVCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fnIEVCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void fnExisteMrCompletedEventHandler(object sender, fnExisteMrCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fnExisteMrCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fnExisteMrCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void fnUltimaSequenciaCompletedEventHandler(object sender, fnUltimaSequenciaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fnUltimaSequenciaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fnUltimaSequenciaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public short Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((short)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void fnCarregaContratoCompletedEventHandler(object sender, fnCarregaContratoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fnCarregaContratoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fnCarregaContratoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void fnDeterminacao_Dados_ContratoCompletedEventHandler(object sender, fnDeterminacao_Dados_ContratoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fnDeterminacao_Dados_ContratoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fnDeterminacao_Dados_ContratoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void fnDeterminacao_Dados_ComercialCompletedEventHandler(object sender, fnDeterminacao_Dados_ComercialCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fnDeterminacao_Dados_ComercialCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fnDeterminacao_Dados_ComercialCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void fnDeterminacao_SelectCompletedEventHandler(object sender, fnDeterminacao_SelectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fnDeterminacao_SelectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fnDeterminacao_SelectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void fnDeterminacaoPendenteCompletedEventHandler(object sender, fnDeterminacaoPendenteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fnDeterminacaoPendenteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fnDeterminacaoPendenteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void fnDeterminacao_Veiculo_SelectCompletedEventHandler(object sender, fnDeterminacao_Veiculo_SelectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fnDeterminacao_Veiculo_SelectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fnDeterminacao_Veiculo_SelectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void fnDeterminacao_DeleteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void fnDeterminacao_InsertCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void fnDeterminacao_ComerciaisCompletedEventHandler(object sender, fnDeterminacao_ComerciaisCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fnDeterminacao_ComerciaisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fnDeterminacao_ComerciaisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void fnExisteComercialCompletedEventHandler(object sender, fnExisteComercialCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fnExisteComercialCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fnExisteComercialCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void fnExcluirComercialCompletedEventHandler(object sender, fnExcluirComercialCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fnExcluirComercialCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fnExcluirComercialCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}
