//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:2.0.50727.5485
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 
namespace MSAClass.AsmxRoteiro_Relatorios {
    using System.Xml.Serialization;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Diagnostics;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="asmxRoteiro_RelatoriosSoap", Namespace="http://tempuri.org/")]
    public partial class asmxRoteiro_Relatorios : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private AuthSoapHd authSoapHdValueField;
        
        private System.Threading.SendOrPostCallback spuCarregarCheckingOperationCompleted;
        
        /// <remarks/>
        public asmxRoteiro_Relatorios() {
            string urlSetting = System.Configuration.ConfigurationManager.AppSettings["url_AsmxRoteiro_Relatorios"];
            if ((urlSetting != null)) {
                this.Url = urlSetting;
            }
            else {
                this.Url = "http://localhost/WebServiceMSA/AsmxRoteiro_Relatorios.asmx";
            }
        }
        
        public AuthSoapHd AuthSoapHdValue {
            get {
                return this.authSoapHdValueField;
            }
            set {
                this.authSoapHdValueField = value;
            }
        }
        
        /// <remarks/>
        public event spuCarregarCheckingCompletedEventHandler spuCarregarCheckingCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSoapHdValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/spuCarregarChecking", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public dtsRoteiro_Relatorios spuCarregarChecking(string strCod_Veiculo, System.DateTime dteData_Exibicao, string strCod_Programa, string strCod_Qualidade, byte byIndica_Falha, byte byIndica_Encaixado, byte byIndica_Ordenado, byte byIndica_Nao_Ordenado, byte byIndica_Canceladas) {
            object[] results = this.Invoke("spuCarregarChecking", new object[] {
                        strCod_Veiculo,
                        dteData_Exibicao,
                        strCod_Programa,
                        strCod_Qualidade,
                        byIndica_Falha,
                        byIndica_Encaixado,
                        byIndica_Ordenado,
                        byIndica_Nao_Ordenado,
                        byIndica_Canceladas});
            return ((dtsRoteiro_Relatorios)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginspuCarregarChecking(string strCod_Veiculo, System.DateTime dteData_Exibicao, string strCod_Programa, string strCod_Qualidade, byte byIndica_Falha, byte byIndica_Encaixado, byte byIndica_Ordenado, byte byIndica_Nao_Ordenado, byte byIndica_Canceladas, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("spuCarregarChecking", new object[] {
                        strCod_Veiculo,
                        dteData_Exibicao,
                        strCod_Programa,
                        strCod_Qualidade,
                        byIndica_Falha,
                        byIndica_Encaixado,
                        byIndica_Ordenado,
                        byIndica_Nao_Ordenado,
                        byIndica_Canceladas}, callback, asyncState);
        }
        
        /// <remarks/>
        public dtsRoteiro_Relatorios EndspuCarregarChecking(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((dtsRoteiro_Relatorios)(results[0]));
        }
        
        /// <remarks/>
        public void spuCarregarCheckingAsync(string strCod_Veiculo, System.DateTime dteData_Exibicao, string strCod_Programa, string strCod_Qualidade, byte byIndica_Falha, byte byIndica_Encaixado, byte byIndica_Ordenado, byte byIndica_Nao_Ordenado, byte byIndica_Canceladas) {
            this.spuCarregarCheckingAsync(strCod_Veiculo, dteData_Exibicao, strCod_Programa, strCod_Qualidade, byIndica_Falha, byIndica_Encaixado, byIndica_Ordenado, byIndica_Nao_Ordenado, byIndica_Canceladas, null);
        }
        
        /// <remarks/>
        public void spuCarregarCheckingAsync(string strCod_Veiculo, System.DateTime dteData_Exibicao, string strCod_Programa, string strCod_Qualidade, byte byIndica_Falha, byte byIndica_Encaixado, byte byIndica_Ordenado, byte byIndica_Nao_Ordenado, byte byIndica_Canceladas, object userState) {
            if ((this.spuCarregarCheckingOperationCompleted == null)) {
                this.spuCarregarCheckingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnspuCarregarCheckingOperationCompleted);
            }
            this.InvokeAsync("spuCarregarChecking", new object[] {
                        strCod_Veiculo,
                        dteData_Exibicao,
                        strCod_Programa,
                        strCod_Qualidade,
                        byIndica_Falha,
                        byIndica_Encaixado,
                        byIndica_Ordenado,
                        byIndica_Nao_Ordenado,
                        byIndica_Canceladas}, this.spuCarregarCheckingOperationCompleted, userState);
        }
        
        private void OnspuCarregarCheckingOperationCompleted(object arg) {
            if ((this.spuCarregarCheckingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.spuCarregarCheckingCompleted(this, new spuCarregarCheckingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class AuthSoapHd : System.Web.Services.Protocols.SoapHeader {
        
        private string strUserNameField;
        
        private string strPasswordField;
        
        private string strKeyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string strUserName {
            get {
                return this.strUserNameField;
            }
            set {
                this.strUserNameField = value;
            }
        }
        
        /// <remarks/>
        public string strPassword {
            get {
                return this.strPasswordField;
            }
            set {
                this.strPasswordField = value;
            }
        }
        
        /// <remarks/>
        public string strKey {
            get {
                return this.strKeyField;
            }
            set {
                this.strKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    // A definição deste tipo foi gerada pela extensão do importador do esquema System.Data.Design.TypedDataSetSchemaImporterExtension.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dtsRoteiro_Relatorios")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dtsRoteiro_Relatorios : global::System.Data.DataSet {
        
        private dtbCheckingDataTable tabledtbChecking;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public dtsRoteiro_Relatorios() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected dtsRoteiro_Relatorios(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["dtbChecking"] != null)) {
                    base.Tables.Add(new dtbCheckingDataTable(ds.Tables["dtbChecking"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public dtbCheckingDataTable dtbChecking {
            get {
                return this.tabledtbChecking;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            dtsRoteiro_Relatorios cln = ((dtsRoteiro_Relatorios)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["dtbChecking"] != null)) {
                    base.Tables.Add(new dtbCheckingDataTable(ds.Tables["dtbChecking"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tabledtbChecking = ((dtbCheckingDataTable)(base.Tables["dtbChecking"]));
            if ((initTable == true)) {
                if ((this.tabledtbChecking != null)) {
                    this.tabledtbChecking.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "dtsRoteiro_Relatorios";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dtsRoteiro_Relatorios.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tabledtbChecking = new dtbCheckingDataTable();
            base.Tables.Add(this.tabledtbChecking);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializedtbChecking() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dtsRoteiro_Relatorios ds = new dtsRoteiro_Relatorios();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void dtbCheckingRowChangeEventHandler(object sender, dtbCheckingRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class dtbCheckingDataTable : global::System.Data.DataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn columnCod_Veiculo;
            
            private global::System.Data.DataColumn columnNome_Veiculo;
            
            private global::System.Data.DataColumn columnData_Exibicao;
            
            private global::System.Data.DataColumn columnHorario_Classificacao;
            
            private global::System.Data.DataColumn columnCod_Programa;
            
            private global::System.Data.DataColumn columnBreaks;
            
            private global::System.Data.DataColumn columnsequencia_intervalo;
            
            private global::System.Data.DataColumn columnIndica_Grade;
            
            private global::System.Data.DataColumn columnChave_Acesso;
            
            private global::System.Data.DataColumn columnCod_Empresa;
            
            private global::System.Data.DataColumn columnNumero_Mr;
            
            private global::System.Data.DataColumn columnSequencia_Mr;
            
            private global::System.Data.DataColumn columnCod_Comercial;
            
            private global::System.Data.DataColumn columnTitulo_Comercial;
            
            private global::System.Data.DataColumn columnNome_Produto;
            
            private global::System.Data.DataColumn columnDuracao;
            
            private global::System.Data.DataColumn columnCod_Tipo_Comercial;
            
            private global::System.Data.DataColumn columnCod_Qualidade;
            
            private global::System.Data.DataColumn columnhorario_exibicao;
            
            private global::System.Data.DataColumn columnDocumento_De;
            
            private global::System.Data.DataColumn columnDocumento_Para;
            
            private global::System.Data.DataColumn columnIndica_Rotativo;
            
            private global::System.Data.DataColumn columnCod_Programa_Ordenado;
            
            private global::System.Data.DataColumn columnIndica_Horario;
            
            private global::System.Data.DataColumn columnIndica_Demanda;
            
            private global::System.Data.DataColumn columnCod_Usuario;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public dtbCheckingDataTable() {
                this.TableName = "dtbChecking";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal dtbCheckingDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected dtbCheckingDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Cod_VeiculoColumn {
                get {
                    return this.columnCod_Veiculo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Nome_VeiculoColumn {
                get {
                    return this.columnNome_Veiculo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Data_ExibicaoColumn {
                get {
                    return this.columnData_Exibicao;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Horario_ClassificacaoColumn {
                get {
                    return this.columnHorario_Classificacao;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Cod_ProgramaColumn {
                get {
                    return this.columnCod_Programa;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn BreaksColumn {
                get {
                    return this.columnBreaks;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn sequencia_intervaloColumn {
                get {
                    return this.columnsequencia_intervalo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Indica_GradeColumn {
                get {
                    return this.columnIndica_Grade;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Chave_AcessoColumn {
                get {
                    return this.columnChave_Acesso;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Cod_EmpresaColumn {
                get {
                    return this.columnCod_Empresa;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Numero_MrColumn {
                get {
                    return this.columnNumero_Mr;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Sequencia_MrColumn {
                get {
                    return this.columnSequencia_Mr;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Cod_ComercialColumn {
                get {
                    return this.columnCod_Comercial;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Titulo_ComercialColumn {
                get {
                    return this.columnTitulo_Comercial;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Nome_ProdutoColumn {
                get {
                    return this.columnNome_Produto;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DuracaoColumn {
                get {
                    return this.columnDuracao;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Cod_Tipo_ComercialColumn {
                get {
                    return this.columnCod_Tipo_Comercial;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Cod_QualidadeColumn {
                get {
                    return this.columnCod_Qualidade;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn horario_exibicaoColumn {
                get {
                    return this.columnhorario_exibicao;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Documento_DeColumn {
                get {
                    return this.columnDocumento_De;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Documento_ParaColumn {
                get {
                    return this.columnDocumento_Para;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Indica_RotativoColumn {
                get {
                    return this.columnIndica_Rotativo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Cod_Programa_OrdenadoColumn {
                get {
                    return this.columnCod_Programa_Ordenado;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Indica_HorarioColumn {
                get {
                    return this.columnIndica_Horario;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Indica_DemandaColumn {
                get {
                    return this.columnIndica_Demanda;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Cod_UsuarioColumn {
                get {
                    return this.columnCod_Usuario;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public dtbCheckingRow this[int index] {
                get {
                    return ((dtbCheckingRow)(this.Rows[index]));
                }
            }
            
            public event dtbCheckingRowChangeEventHandler dtbCheckingRowChanging;
            
            public event dtbCheckingRowChangeEventHandler dtbCheckingRowChanged;
            
            public event dtbCheckingRowChangeEventHandler dtbCheckingRowDeleting;
            
            public event dtbCheckingRowChangeEventHandler dtbCheckingRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AdddtbCheckingRow(dtbCheckingRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public dtbCheckingRow AdddtbCheckingRow(
                        string Cod_Veiculo, 
                        string Nome_Veiculo, 
                        System.DateTime Data_Exibicao, 
                        int Horario_Classificacao, 
                        string Cod_Programa, 
                        short Breaks, 
                        short sequencia_intervalo, 
                        byte Indica_Grade, 
                        short Chave_Acesso, 
                        string Cod_Empresa, 
                        int Numero_Mr, 
                        short Sequencia_Mr, 
                        string Cod_Comercial, 
                        string Titulo_Comercial, 
                        string Nome_Produto, 
                        int Duracao, 
                        string Cod_Tipo_Comercial, 
                        string Cod_Qualidade, 
                        System.DateTime horario_exibicao, 
                        string Documento_De, 
                        string Documento_Para, 
                        byte Indica_Rotativo, 
                        string Cod_Programa_Ordenado, 
                        byte Indica_Horario, 
                        byte Indica_Demanda, 
                        string Cod_Usuario) {
                dtbCheckingRow rowdtbCheckingRow = ((dtbCheckingRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        Cod_Veiculo,
                        Nome_Veiculo,
                        Data_Exibicao,
                        Horario_Classificacao,
                        Cod_Programa,
                        Breaks,
                        sequencia_intervalo,
                        Indica_Grade,
                        Chave_Acesso,
                        Cod_Empresa,
                        Numero_Mr,
                        Sequencia_Mr,
                        Cod_Comercial,
                        Titulo_Comercial,
                        Nome_Produto,
                        Duracao,
                        Cod_Tipo_Comercial,
                        Cod_Qualidade,
                        horario_exibicao,
                        Documento_De,
                        Documento_Para,
                        Indica_Rotativo,
                        Cod_Programa_Ordenado,
                        Indica_Horario,
                        Indica_Demanda,
                        Cod_Usuario};
                rowdtbCheckingRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowdtbCheckingRow);
                return rowdtbCheckingRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                dtbCheckingDataTable cln = ((dtbCheckingDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new dtbCheckingDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnCod_Veiculo = base.Columns["Cod_Veiculo"];
                this.columnNome_Veiculo = base.Columns["Nome_Veiculo"];
                this.columnData_Exibicao = base.Columns["Data_Exibicao"];
                this.columnHorario_Classificacao = base.Columns["Horario_Classificacao"];
                this.columnCod_Programa = base.Columns["Cod_Programa"];
                this.columnBreaks = base.Columns["Breaks"];
                this.columnsequencia_intervalo = base.Columns["sequencia_intervalo"];
                this.columnIndica_Grade = base.Columns["Indica_Grade"];
                this.columnChave_Acesso = base.Columns["Chave_Acesso"];
                this.columnCod_Empresa = base.Columns["Cod_Empresa"];
                this.columnNumero_Mr = base.Columns["Numero_Mr"];
                this.columnSequencia_Mr = base.Columns["Sequencia_Mr"];
                this.columnCod_Comercial = base.Columns["Cod_Comercial"];
                this.columnTitulo_Comercial = base.Columns["Titulo_Comercial"];
                this.columnNome_Produto = base.Columns["Nome_Produto"];
                this.columnDuracao = base.Columns["Duracao"];
                this.columnCod_Tipo_Comercial = base.Columns["Cod_Tipo_Comercial"];
                this.columnCod_Qualidade = base.Columns["Cod_Qualidade"];
                this.columnhorario_exibicao = base.Columns["horario_exibicao"];
                this.columnDocumento_De = base.Columns["Documento_De"];
                this.columnDocumento_Para = base.Columns["Documento_Para"];
                this.columnIndica_Rotativo = base.Columns["Indica_Rotativo"];
                this.columnCod_Programa_Ordenado = base.Columns["Cod_Programa_Ordenado"];
                this.columnIndica_Horario = base.Columns["Indica_Horario"];
                this.columnIndica_Demanda = base.Columns["Indica_Demanda"];
                this.columnCod_Usuario = base.Columns["Cod_Usuario"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnCod_Veiculo = new global::System.Data.DataColumn("Cod_Veiculo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCod_Veiculo);
                this.columnNome_Veiculo = new global::System.Data.DataColumn("Nome_Veiculo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNome_Veiculo);
                this.columnData_Exibicao = new global::System.Data.DataColumn("Data_Exibicao", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnData_Exibicao);
                this.columnHorario_Classificacao = new global::System.Data.DataColumn("Horario_Classificacao", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnHorario_Classificacao);
                this.columnCod_Programa = new global::System.Data.DataColumn("Cod_Programa", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCod_Programa);
                this.columnBreaks = new global::System.Data.DataColumn("Breaks", typeof(short), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBreaks);
                this.columnsequencia_intervalo = new global::System.Data.DataColumn("sequencia_intervalo", typeof(short), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnsequencia_intervalo);
                this.columnIndica_Grade = new global::System.Data.DataColumn("Indica_Grade", typeof(byte), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIndica_Grade);
                this.columnChave_Acesso = new global::System.Data.DataColumn("Chave_Acesso", typeof(short), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnChave_Acesso);
                this.columnCod_Empresa = new global::System.Data.DataColumn("Cod_Empresa", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCod_Empresa);
                this.columnNumero_Mr = new global::System.Data.DataColumn("Numero_Mr", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNumero_Mr);
                this.columnSequencia_Mr = new global::System.Data.DataColumn("Sequencia_Mr", typeof(short), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSequencia_Mr);
                this.columnCod_Comercial = new global::System.Data.DataColumn("Cod_Comercial", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCod_Comercial);
                this.columnTitulo_Comercial = new global::System.Data.DataColumn("Titulo_Comercial", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTitulo_Comercial);
                this.columnNome_Produto = new global::System.Data.DataColumn("Nome_Produto", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNome_Produto);
                this.columnDuracao = new global::System.Data.DataColumn("Duracao", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDuracao);
                this.columnCod_Tipo_Comercial = new global::System.Data.DataColumn("Cod_Tipo_Comercial", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCod_Tipo_Comercial);
                this.columnCod_Qualidade = new global::System.Data.DataColumn("Cod_Qualidade", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCod_Qualidade);
                this.columnhorario_exibicao = new global::System.Data.DataColumn("horario_exibicao", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnhorario_exibicao);
                this.columnDocumento_De = new global::System.Data.DataColumn("Documento_De", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDocumento_De);
                this.columnDocumento_Para = new global::System.Data.DataColumn("Documento_Para", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDocumento_Para);
                this.columnIndica_Rotativo = new global::System.Data.DataColumn("Indica_Rotativo", typeof(byte), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIndica_Rotativo);
                this.columnCod_Programa_Ordenado = new global::System.Data.DataColumn("Cod_Programa_Ordenado", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCod_Programa_Ordenado);
                this.columnIndica_Horario = new global::System.Data.DataColumn("Indica_Horario", typeof(byte), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIndica_Horario);
                this.columnIndica_Demanda = new global::System.Data.DataColumn("Indica_Demanda", typeof(byte), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIndica_Demanda);
                this.columnCod_Usuario = new global::System.Data.DataColumn("Cod_Usuario", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCod_Usuario);
                this.columnCod_Veiculo.MaxLength = 3;
                this.columnNome_Veiculo.MaxLength = 50;
                this.columnData_Exibicao.DateTimeMode = global::System.Data.DataSetDateTime.Unspecified;
                this.columnCod_Programa.MaxLength = 4;
                this.columnCod_Empresa.MaxLength = 3;
                this.columnCod_Comercial.MaxLength = 2;
                this.columnTitulo_Comercial.MaxLength = 30;
                this.columnNome_Produto.MaxLength = 40;
                this.columnCod_Tipo_Comercial.MaxLength = 2;
                this.columnCod_Qualidade.MaxLength = 3;
                this.columnDocumento_De.MaxLength = 8;
                this.columnDocumento_Para.MaxLength = 8;
                this.columnCod_Programa_Ordenado.MaxLength = 4;
                this.columnCod_Usuario.MaxLength = 20;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public dtbCheckingRow NewdtbCheckingRow() {
                return ((dtbCheckingRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new dtbCheckingRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(dtbCheckingRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.dtbCheckingRowChanged != null)) {
                    this.dtbCheckingRowChanged(this, new dtbCheckingRowChangeEvent(((dtbCheckingRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.dtbCheckingRowChanging != null)) {
                    this.dtbCheckingRowChanging(this, new dtbCheckingRowChangeEvent(((dtbCheckingRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.dtbCheckingRowDeleted != null)) {
                    this.dtbCheckingRowDeleted(this, new dtbCheckingRowChangeEvent(((dtbCheckingRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.dtbCheckingRowDeleting != null)) {
                    this.dtbCheckingRowDeleting(this, new dtbCheckingRowChangeEvent(((dtbCheckingRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemovedtbCheckingRow(dtbCheckingRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dtsRoteiro_Relatorios ds = new dtsRoteiro_Relatorios();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "dtbCheckingDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class dtbCheckingRow : global::System.Data.DataRow {
            
            private dtbCheckingDataTable tabledtbChecking;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal dtbCheckingRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tabledtbChecking = ((dtbCheckingDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Cod_Veiculo {
                get {
                    try {
                        return ((string)(this[this.tabledtbChecking.Cod_VeiculoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Cod_Veiculo\' na tabela \'dtbChecking\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbChecking.Cod_VeiculoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Nome_Veiculo {
                get {
                    try {
                        return ((string)(this[this.tabledtbChecking.Nome_VeiculoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Nome_Veiculo\' na tabela \'dtbChecking\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbChecking.Nome_VeiculoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime Data_Exibicao {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tabledtbChecking.Data_ExibicaoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Data_Exibicao\' na tabela \'dtbChecking\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbChecking.Data_ExibicaoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int Horario_Classificacao {
                get {
                    try {
                        return ((int)(this[this.tabledtbChecking.Horario_ClassificacaoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Horario_Classificacao\' na tabela \'dtbChecking\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbChecking.Horario_ClassificacaoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Cod_Programa {
                get {
                    try {
                        return ((string)(this[this.tabledtbChecking.Cod_ProgramaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Cod_Programa\' na tabela \'dtbChecking\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbChecking.Cod_ProgramaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public short Breaks {
                get {
                    try {
                        return ((short)(this[this.tabledtbChecking.BreaksColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Breaks\' na tabela \'dtbChecking\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbChecking.BreaksColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public short sequencia_intervalo {
                get {
                    try {
                        return ((short)(this[this.tabledtbChecking.sequencia_intervaloColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'sequencia_intervalo\' na tabela \'dtbChecking\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbChecking.sequencia_intervaloColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public byte Indica_Grade {
                get {
                    try {
                        return ((byte)(this[this.tabledtbChecking.Indica_GradeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Indica_Grade\' na tabela \'dtbChecking\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbChecking.Indica_GradeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public short Chave_Acesso {
                get {
                    try {
                        return ((short)(this[this.tabledtbChecking.Chave_AcessoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Chave_Acesso\' na tabela \'dtbChecking\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbChecking.Chave_AcessoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Cod_Empresa {
                get {
                    try {
                        return ((string)(this[this.tabledtbChecking.Cod_EmpresaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Cod_Empresa\' na tabela \'dtbChecking\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbChecking.Cod_EmpresaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int Numero_Mr {
                get {
                    try {
                        return ((int)(this[this.tabledtbChecking.Numero_MrColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Numero_Mr\' na tabela \'dtbChecking\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbChecking.Numero_MrColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public short Sequencia_Mr {
                get {
                    try {
                        return ((short)(this[this.tabledtbChecking.Sequencia_MrColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Sequencia_Mr\' na tabela \'dtbChecking\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbChecking.Sequencia_MrColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Cod_Comercial {
                get {
                    try {
                        return ((string)(this[this.tabledtbChecking.Cod_ComercialColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Cod_Comercial\' na tabela \'dtbChecking\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbChecking.Cod_ComercialColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Titulo_Comercial {
                get {
                    try {
                        return ((string)(this[this.tabledtbChecking.Titulo_ComercialColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Titulo_Comercial\' na tabela \'dtbChecking\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbChecking.Titulo_ComercialColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Nome_Produto {
                get {
                    try {
                        return ((string)(this[this.tabledtbChecking.Nome_ProdutoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Nome_Produto\' na tabela \'dtbChecking\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbChecking.Nome_ProdutoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int Duracao {
                get {
                    try {
                        return ((int)(this[this.tabledtbChecking.DuracaoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Duracao\' na tabela \'dtbChecking\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbChecking.DuracaoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Cod_Tipo_Comercial {
                get {
                    try {
                        return ((string)(this[this.tabledtbChecking.Cod_Tipo_ComercialColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Cod_Tipo_Comercial\' na tabela \'dtbChecking\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbChecking.Cod_Tipo_ComercialColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Cod_Qualidade {
                get {
                    try {
                        return ((string)(this[this.tabledtbChecking.Cod_QualidadeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Cod_Qualidade\' na tabela \'dtbChecking\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbChecking.Cod_QualidadeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime horario_exibicao {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tabledtbChecking.horario_exibicaoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'horario_exibicao\' na tabela \'dtbChecking\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbChecking.horario_exibicaoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Documento_De {
                get {
                    try {
                        return ((string)(this[this.tabledtbChecking.Documento_DeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Documento_De\' na tabela \'dtbChecking\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbChecking.Documento_DeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Documento_Para {
                get {
                    try {
                        return ((string)(this[this.tabledtbChecking.Documento_ParaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Documento_Para\' na tabela \'dtbChecking\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbChecking.Documento_ParaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public byte Indica_Rotativo {
                get {
                    try {
                        return ((byte)(this[this.tabledtbChecking.Indica_RotativoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Indica_Rotativo\' na tabela \'dtbChecking\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbChecking.Indica_RotativoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Cod_Programa_Ordenado {
                get {
                    try {
                        return ((string)(this[this.tabledtbChecking.Cod_Programa_OrdenadoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Cod_Programa_Ordenado\' na tabela \'dtbChecking\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbChecking.Cod_Programa_OrdenadoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public byte Indica_Horario {
                get {
                    try {
                        return ((byte)(this[this.tabledtbChecking.Indica_HorarioColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Indica_Horario\' na tabela \'dtbChecking\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbChecking.Indica_HorarioColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public byte Indica_Demanda {
                get {
                    try {
                        return ((byte)(this[this.tabledtbChecking.Indica_DemandaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Indica_Demanda\' na tabela \'dtbChecking\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbChecking.Indica_DemandaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Cod_Usuario {
                get {
                    try {
                        return ((string)(this[this.tabledtbChecking.Cod_UsuarioColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'Cod_Usuario\' na tabela \'dtbChecking\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbChecking.Cod_UsuarioColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCod_VeiculoNull() {
                return this.IsNull(this.tabledtbChecking.Cod_VeiculoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCod_VeiculoNull() {
                this[this.tabledtbChecking.Cod_VeiculoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsNome_VeiculoNull() {
                return this.IsNull(this.tabledtbChecking.Nome_VeiculoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetNome_VeiculoNull() {
                this[this.tabledtbChecking.Nome_VeiculoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsData_ExibicaoNull() {
                return this.IsNull(this.tabledtbChecking.Data_ExibicaoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetData_ExibicaoNull() {
                this[this.tabledtbChecking.Data_ExibicaoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsHorario_ClassificacaoNull() {
                return this.IsNull(this.tabledtbChecking.Horario_ClassificacaoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetHorario_ClassificacaoNull() {
                this[this.tabledtbChecking.Horario_ClassificacaoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCod_ProgramaNull() {
                return this.IsNull(this.tabledtbChecking.Cod_ProgramaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCod_ProgramaNull() {
                this[this.tabledtbChecking.Cod_ProgramaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsBreaksNull() {
                return this.IsNull(this.tabledtbChecking.BreaksColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetBreaksNull() {
                this[this.tabledtbChecking.BreaksColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Issequencia_intervaloNull() {
                return this.IsNull(this.tabledtbChecking.sequencia_intervaloColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setsequencia_intervaloNull() {
                this[this.tabledtbChecking.sequencia_intervaloColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsIndica_GradeNull() {
                return this.IsNull(this.tabledtbChecking.Indica_GradeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetIndica_GradeNull() {
                this[this.tabledtbChecking.Indica_GradeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsChave_AcessoNull() {
                return this.IsNull(this.tabledtbChecking.Chave_AcessoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetChave_AcessoNull() {
                this[this.tabledtbChecking.Chave_AcessoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCod_EmpresaNull() {
                return this.IsNull(this.tabledtbChecking.Cod_EmpresaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCod_EmpresaNull() {
                this[this.tabledtbChecking.Cod_EmpresaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsNumero_MrNull() {
                return this.IsNull(this.tabledtbChecking.Numero_MrColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetNumero_MrNull() {
                this[this.tabledtbChecking.Numero_MrColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSequencia_MrNull() {
                return this.IsNull(this.tabledtbChecking.Sequencia_MrColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSequencia_MrNull() {
                this[this.tabledtbChecking.Sequencia_MrColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCod_ComercialNull() {
                return this.IsNull(this.tabledtbChecking.Cod_ComercialColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCod_ComercialNull() {
                this[this.tabledtbChecking.Cod_ComercialColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTitulo_ComercialNull() {
                return this.IsNull(this.tabledtbChecking.Titulo_ComercialColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTitulo_ComercialNull() {
                this[this.tabledtbChecking.Titulo_ComercialColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsNome_ProdutoNull() {
                return this.IsNull(this.tabledtbChecking.Nome_ProdutoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetNome_ProdutoNull() {
                this[this.tabledtbChecking.Nome_ProdutoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDuracaoNull() {
                return this.IsNull(this.tabledtbChecking.DuracaoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDuracaoNull() {
                this[this.tabledtbChecking.DuracaoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCod_Tipo_ComercialNull() {
                return this.IsNull(this.tabledtbChecking.Cod_Tipo_ComercialColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCod_Tipo_ComercialNull() {
                this[this.tabledtbChecking.Cod_Tipo_ComercialColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCod_QualidadeNull() {
                return this.IsNull(this.tabledtbChecking.Cod_QualidadeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCod_QualidadeNull() {
                this[this.tabledtbChecking.Cod_QualidadeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Ishorario_exibicaoNull() {
                return this.IsNull(this.tabledtbChecking.horario_exibicaoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Sethorario_exibicaoNull() {
                this[this.tabledtbChecking.horario_exibicaoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDocumento_DeNull() {
                return this.IsNull(this.tabledtbChecking.Documento_DeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDocumento_DeNull() {
                this[this.tabledtbChecking.Documento_DeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDocumento_ParaNull() {
                return this.IsNull(this.tabledtbChecking.Documento_ParaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDocumento_ParaNull() {
                this[this.tabledtbChecking.Documento_ParaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsIndica_RotativoNull() {
                return this.IsNull(this.tabledtbChecking.Indica_RotativoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetIndica_RotativoNull() {
                this[this.tabledtbChecking.Indica_RotativoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCod_Programa_OrdenadoNull() {
                return this.IsNull(this.tabledtbChecking.Cod_Programa_OrdenadoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCod_Programa_OrdenadoNull() {
                this[this.tabledtbChecking.Cod_Programa_OrdenadoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsIndica_HorarioNull() {
                return this.IsNull(this.tabledtbChecking.Indica_HorarioColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetIndica_HorarioNull() {
                this[this.tabledtbChecking.Indica_HorarioColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsIndica_DemandaNull() {
                return this.IsNull(this.tabledtbChecking.Indica_DemandaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetIndica_DemandaNull() {
                this[this.tabledtbChecking.Indica_DemandaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCod_UsuarioNull() {
                return this.IsNull(this.tabledtbChecking.Cod_UsuarioColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCod_UsuarioNull() {
                this[this.tabledtbChecking.Cod_UsuarioColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class dtbCheckingRowChangeEvent : global::System.EventArgs {
            
            private dtbCheckingRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public dtbCheckingRowChangeEvent(dtbCheckingRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public dtbCheckingRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void spuCarregarCheckingCompletedEventHandler(object sender, spuCarregarCheckingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class spuCarregarCheckingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal spuCarregarCheckingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public dtsRoteiro_Relatorios Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((dtsRoteiro_Relatorios)(this.results[0]));
            }
        }
    }
}
