Echo Off
echo =========================AsmxAM
wsdl.exe  http://localhost/WebServiceMSA/AsmxAM.asmx /namespace:MSAClass.AsmxAM /urlkey:url_AsmxAM
echo =========================
Echo Off
echo =========================AsmxBaixaVeiculacao
wsdl.exe  http://localhost/WebServiceMSA/AsmxBaixaVeiculacao.asmx /namespace:MSAClass.AsmxBaixaVeiculacao /urlkey:url_AsmxBaixaVeiculacao
echo =========================
Echo Off
echo =========================AsmxBreak
wsdl.exe  http://localhost/WebServiceMSA/AsmxBreak.asmx /namespace:MSAClass.AsmxBreak /urlkey:url_AsmxBreak
echo =========================
Echo Off
echo =========================AsmxChecking
wsdl.exe  http://localhost/WebServiceMSA/AsmxChecking.asmx /namespace:MSAClass.AsmxChecking /urlkey:url_AsmxChecking
echo =========================
Echo Off
echo =========================AsmxContato
wsdl.exe  http://localhost/WebServiceMSA/AsmxContato.asmx /namespace:MSAClass.AsmxContato /urlkey:url_AsmxContato
echo =========================
Echo Off
echo =========================AsmxContrato
wsdl.exe  http://localhost/WebServiceMSA/AsmxContrato.asmx /namespace:MSAClass.AsmxContrato /urlkey:url_AsmxContrato
echo =========================
Echo Off
echo =========================AsmxControleFita
wsdl.exe  http://localhost/WebServiceMSA/AsmxControleFita.asmx /namespace:MSAClass.AsmxControleFita /urlkey:url_AsmxControleFita
echo =========================
Echo Off
echo =========================AsmxEmpresa
wsdl.exe  http://localhost/WebServiceMSA/AsmxEmpresa.asmx /namespace:MSAClass.AsmxEmpresa /urlkey:url_AsmxEmpresa
echo =========================
Echo Off
echo =========================AsmxFaixaHoraria
wsdl.exe  http://localhost/WebServiceMSA/AsmxFaixaHoraria.asmx /namespace:MSAClass.AsmxFaixaHoraria /urlkey:url_AsmxFaixaHoraria
echo =========================
Echo Off
echo =========================AsmxFita_Ordenada
wsdl.exe  http://localhost/WebServiceMSA/AsmxFita_Ordenada.asmx /namespace:MSAClass.AsmxFita_Ordenada /urlkey:url_AsmxFita_Ordenada
echo =========================
Echo Off
echo =========================AsmxGeneric
wsdl.exe  http://localhost/WebServiceMSA/AsmxGeneric.asmx /namespace:MSAClass.AsmxGeneric /urlkey:url_AsmxGeneric
echo =========================
Echo Off
echo =========================AsmxGrade
wsdl.exe  http://localhost/WebServiceMSA/AsmxGrade.asmx /namespace:MSAClass.AsmxGrade /urlkey:url_AsmxGrade
echo =========================
Echo Off
echo =========================AsmxHistoricoMr
wsdl.exe  http://localhost/WebServiceMSA/AsmxHistoricoMr.asmx /namespace:MSAClass.AsmxHistoricoMr /urlkey:url_AsmxHistoricoMr
echo =========================
Echo Off
echo =========================AsmxMotivo
wsdl.exe  http://localhost/WebServiceMSA/AsmxMotivo.asmx /namespace:MSAClass.AsmxMotivo /urlkey:url_AsmxMotivo
echo =========================
Echo Off
echo =========================AsmxNaturezaServico
wsdl.exe  http://localhost/WebServiceMSA/AsmxNaturezaServico.asmx /namespace:MSAClass.AsmxNaturezaServico /urlkey:url_AsmxNaturezaServico
echo =========================
Echo Off
echo =========================AsmxNucleo
wsdl.exe  http://localhost/WebServiceMSA/AsmxNucleo.asmx /namespace:MSAClass.AsmxNucleo /urlkey:url_AsmxNucleo
echo =========================
Echo Off
echo =========================AsmxParametro
wsdl.exe  http://localhost/WebServiceMSA/AsmxParametro.asmx /namespace:MSAClass.AsmxParametro /urlkey:url_AsmxParametro
echo =========================
Echo Off
echo =========================AsmxParametro_Roteiro
wsdl.exe  http://localhost/WebServiceMSA/AsmxParametro_Roteiro.asmx /namespace:MSAClass.AsmxParametro_Roteiro /urlkey:url_AsmxParametro_Roteiro
echo =========================
Echo Off
echo =========================AsmxPorta
wsdl.exe  http://localhost/WebServiceMSA/AsmxPorta.asmx /namespace:MSAClass.AsmxPorta /urlkey:url_AsmxPorta
echo =========================
Echo Off
echo =========================AsmxProduto
wsdl.exe  http://localhost/WebServiceMSA/AsmxProduto.asmx /namespace:MSAClass.AsmxProduto /urlkey:url_AsmxProduto
echo =========================
Echo Off
echo =========================AsmxPrograma
wsdl.exe  http://localhost/WebServiceMSA/AsmxPrograma.asmx /namespace:MSAClass.AsmxPrograma /urlkey:url_AsmxPrograma
echo =========================
Echo Off
echo =========================AsmxQualidade
wsdl.exe  http://localhost/WebServiceMSA/AsmxQualidade.asmx /namespace:MSAClass.AsmxQualidade /urlkey:url_AsmxQualidade
echo =========================
Echo Off
echo =========================AsmxRetornoPlayList
wsdl.exe  http://localhost/WebServiceMSA/AsmxRetornoPlayList.asmx /namespace:MSAClass.AsmxRetornoPlayList /urlkey:url_AsmxRetornoPlayList
echo =========================
Echo Off
echo =========================AsmxRoteiro
wsdl.exe  http://localhost/WebServiceMSA/AsmxRoteiro.asmx /namespace:MSAClass.AsmxRoteiro /urlkey:url_AsmxRoteiro
echo =========================
Echo Off
echo =========================AsmxRoteiroLog
wsdl.exe  http://localhost/WebServiceMSA/AsmxRoteiroLog.asmx /namespace:MSAClass.AsmxRoteiroLog /urlkey:url_AsmxRoteiroLog
echo =========================
Echo Off
echo =========================AsmxRoteiro_Confirmacao
wsdl.exe  http://localhost/WebServiceMSA/AsmxRoteiro_Confirmacao.asmx /namespace:MSAClass.AsmxRoteiro_Confirmacao /urlkey:url_AsmxRoteiro_Confirmacao
echo =========================
Echo Off
echo =========================AsmxRoteiro_Relatorios
wsdl.exe  http://localhost/WebServiceMSA/AsmxRoteiro_Relatorios.asmx /namespace:MSAClass.AsmxRoteiro_Relatorios /urlkey:url_AsmxRoteiro_Relatorios
echo =========================
Echo Off
echo =========================AsmxTerceiro
wsdl.exe  http://localhost/WebServiceMSA/AsmxTerceiro.asmx /namespace:MSAClass.AsmxTerceiro /urlkey:url_AsmxTerceiro
echo =========================
Echo Off
echo =========================AsmxTipoComercial
wsdl.exe  http://localhost/WebServiceMSA/AsmxTipoComercial.asmx /namespace:MSAClass.AsmxTipoComercial /urlkey:url_AsmxTipoComercial
echo =========================
Echo Off
echo =========================AsmxTipoMidia
wsdl.exe  http://localhost/WebServiceMSA/AsmxTipoMidia.asmx /namespace:MSAClass.AsmxTipoMidia /urlkey:url_AsmxTipoMidia
echo =========================
Echo Off
echo =========================AsmxUsuario
wsdl.exe  http://localhost/WebServiceMSA/AsmxUsuario.asmx /namespace:MSAClass.AsmxUsuario /urlkey:url_AsmxUsuario
echo =========================
Echo Off
echo =========================AsmxVeiculo
wsdl.exe  http://localhost/WebServiceMSA/AsmxVeiculo.asmx /namespace:MSAClass.AsmxVeiculo /urlkey:url_AsmxVeiculo
echo =========================
echo =========================AsmxVeiculo
wsdl.exe  http://localhost/WebServiceMSA/asmxMacAddress.asmx /namespace:MSAClass.asmxMacAddress /urlkey:asmxMacAddress
echo =========================


